# Form implementation generated from reading ui file 'd:\Bachelor_GUI\gui\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(1483, 930)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1462, 930))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        self.styleSheet.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.styleSheet.setFont(font)
        self.styleSheet.setObjectName("styleSheet")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.styleSheet)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.bgApp = QtWidgets.QFrame(self.styleSheet)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bgApp.setFont(font)
        self.bgApp.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bgApp.setObjectName("bgApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.contentBox = QtWidgets.QFrame(self.bgApp)
        self.contentBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentBottom = QtWidgets.QFrame(self.contentBox)
        self.contentBottom.setStyleSheet("")
        self.contentBottom.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.contentBottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.content = QtWidgets.QFrame(self.contentBottom)
        self.content.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pagesContainer = QtWidgets.QFrame(self.content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pagesContainer.sizePolicy().hasHeightForWidth())
        self.pagesContainer.setSizePolicy(sizePolicy)
        self.pagesContainer.setStyleSheet("")
        self.pagesContainer.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.pagesContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pagesContainer.setObjectName("pagesContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pagesContainer)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.pagesContainer)
        self.tabWidget.setMinimumSize(QtCore.QSize(1232, 890))
        self.tabWidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.482955, y1:1, x2:0.489, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(4, 38, 53, 255));")
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabWidgetPage1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.row = QtWidgets.QFrame(self.tabWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.row.sizePolicy().hasHeightForWidth())
        self.row.setSizePolicy(sizePolicy)
        self.row.setMinimumSize(QtCore.QSize(0, 0))
        self.row.setStyleSheet("")
        self.row.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.row.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.row.setObjectName("row")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.row)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.column1 = QtWidgets.QFrame(self.row)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.column1.sizePolicy().hasHeightForWidth())
        self.column1.setSizePolicy(sizePolicy)
        self.column1.setMinimumSize(QtCore.QSize(0, 0))
        self.column1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.column1.setSizeIncrement(QtCore.QSize(0, 0))
        self.column1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.column1.setFont(font)
        self.column1.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.column1.setObjectName("column1")
        self.column1Layout = QtWidgets.QVBoxLayout(self.column1)
        self.column1Layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.column1Layout.setContentsMargins(-1, -1, 12, -1)
        self.column1Layout.setSpacing(5)
        self.column1Layout.setObjectName("column1Layout")
        self.title_kjoremodus = QtWidgets.QLabel(self.column1)
        self.title_kjoremodus.setMinimumSize(QtCore.QSize(0, 0))
        self.title_kjoremodus.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_kjoremodus.setFont(font)
        self.title_kjoremodus.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.title_kjoremodus.setObjectName("title_kjoremodus")
        self.column1Layout.addWidget(self.title_kjoremodus)
        self.frame = QtWidgets.QFrame(self.column1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setObjectName("frame")
        self.kjoremodusLayout = QtWidgets.QVBoxLayout(self.frame)
        self.kjoremodusLayout.setContentsMargins(0, 0, 0, 0)
        self.kjoremodusLayout.setSpacing(5)
        self.kjoremodusLayout.setObjectName("kjoremodusLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(351, 359))
        self.frame_2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(-1, 1, 351, 359))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(351, 359))
        self.label_20.setMaximumSize(QtCore.QSize(351, 359))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/rov/E:/image.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.labelVVF_3 = QtWidgets.QLabel(self.frame_2)
        self.labelVVF_3.setGeometry(QtCore.QRect(0, 20, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVVF_3.sizePolicy().hasHeightForWidth())
        self.labelVVF_3.setSizePolicy(sizePolicy)
        self.labelVVF_3.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.labelVVF_3.setObjectName("labelVVF_3")
        self.labelVHF_3 = QtWidgets.QLabel(self.frame_2)
        self.labelVHF_3.setGeometry(QtCore.QRect(300, 20, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVHF_3.sizePolicy().hasHeightForWidth())
        self.labelVHF_3.setSizePolicy(sizePolicy)
        self.labelVHF_3.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.labelVHF_3.setObjectName("labelVHF_3")
        self.labelHHF_3 = QtWidgets.QLabel(self.frame_2)
        self.labelHHF_3.setGeometry(QtCore.QRect(220, 70, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHHF_3.sizePolicy().hasHeightForWidth())
        self.labelHHF_3.setSizePolicy(sizePolicy)
        self.labelHHF_3.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.labelHHF_3.setObjectName("labelHHF_3")
        self.labelHHB_3 = QtWidgets.QLabel(self.frame_2)
        self.labelHHB_3.setGeometry(QtCore.QRect(220, 160, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHHB_3.sizePolicy().hasHeightForWidth())
        self.labelHHB_3.setSizePolicy(sizePolicy)
        self.labelHHB_3.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.labelHHB_3.setObjectName("labelHHB_3")
        self.labelVHB_3 = QtWidgets.QLabel(self.frame_2)
        self.labelVHB_3.setGeometry(QtCore.QRect(290, 230, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVHB_3.sizePolicy().hasHeightForWidth())
        self.labelVHB_3.setSizePolicy(sizePolicy)
        self.labelVHB_3.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.labelVHB_3.setObjectName("labelVHB_3")
        self.labelVVB_3 = QtWidgets.QLabel(self.frame_2)
        self.labelVVB_3.setGeometry(QtCore.QRect(10, 230, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVVB_3.sizePolicy().hasHeightForWidth())
        self.labelVVB_3.setSizePolicy(sizePolicy)
        self.labelVVB_3.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.labelVVB_3.setObjectName("labelVVB_3")
        self.labelHVB_3 = QtWidgets.QLabel(self.frame_2)
        self.labelHVB_3.setGeometry(QtCore.QRect(80, 160, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHVB_3.sizePolicy().hasHeightForWidth())
        self.labelHVB_3.setSizePolicy(sizePolicy)
        self.labelHVB_3.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.labelHVB_3.setObjectName("labelHVB_3")
        self.labelHVF_3 = QtWidgets.QLabel(self.frame_2)
        self.labelHVF_3.setGeometry(QtCore.QRect(80, 70, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHVF_3.sizePolicy().hasHeightForWidth())
        self.labelHVF_3.setSizePolicy(sizePolicy)
        self.labelHVF_3.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.labelHVF_3.setObjectName("labelHVF_3")
        self.kjoremodusLayout.addWidget(self.frame_2)
        self.title_kjoremodus_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_kjoremodus_2.sizePolicy().hasHeightForWidth())
        self.title_kjoremodus_2.setSizePolicy(sizePolicy)
        self.title_kjoremodus_2.setMinimumSize(QtCore.QSize(351, 0))
        self.title_kjoremodus_2.setMaximumSize(QtCore.QSize(90, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_kjoremodus_2.setFont(font)
        self.title_kjoremodus_2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.title_kjoremodus_2.setObjectName("title_kjoremodus_2")
        self.kjoremodusLayout.addWidget(self.title_kjoremodus_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_38.addWidget(self.label_12)
        self.horizontalLayout_7.addLayout(self.verticalLayout_38)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.labelManipulatorTemp = QtWidgets.QLabel(self.frame)
        self.labelManipulatorTemp.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.labelManipulatorTemp.setText("")
        self.labelManipulatorTemp.setObjectName("labelManipulatorTemp")
        self.verticalLayout_39.addWidget(self.labelManipulatorTemp)
        self.labelThruster12VTemp = QtWidgets.QLabel(self.frame)
        self.labelThruster12VTemp.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.labelThruster12VTemp.setText("")
        self.labelThruster12VTemp.setObjectName("labelThruster12VTemp")
        self.verticalLayout_39.addWidget(self.labelThruster12VTemp)
        self.labelTempVann = QtWidgets.QLabel(self.frame)
        self.labelTempVann.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.labelTempVann.setText("")
        self.labelTempVann.setObjectName("labelTempVann")
        self.verticalLayout_39.addWidget(self.labelTempVann)
        self.labelTempSensorkort = QtWidgets.QLabel(self.frame)
        self.labelTempSensorkort.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.labelTempSensorkort.setText("")
        self.labelTempSensorkort.setObjectName("labelTempSensorkort")
        self.verticalLayout_39.addWidget(self.labelTempSensorkort)
        self.horizontalLayout_7.addLayout(self.verticalLayout_39)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_7)
        self.kjoremodusLayout.addLayout(self.horizontalLayout_3)
        self.column1Layout.addWidget(self.frame)
        self.horizontalLayout_6.addWidget(self.column1)
        self.column3 = QtWidgets.QFrame(self.row)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.column3.sizePolicy().hasHeightForWidth())
        self.column3.setSizePolicy(sizePolicy)
        self.column3.setMinimumSize(QtCore.QSize(0, 0))
        self.column3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.column3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        self.column3.setFont(font)
        self.column3.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.column3.setObjectName("column3")
        self.column3Layout = QtWidgets.QVBoxLayout(self.column3)
        self.column3Layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.column3Layout.setSpacing(5)
        self.column3Layout.setObjectName("column3Layout")
        self.Overskriftkamera_4 = QtWidgets.QFrame(self.column3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Overskriftkamera_4.sizePolicy().hasHeightForWidth())
        self.Overskriftkamera_4.setSizePolicy(sizePolicy)
        self.Overskriftkamera_4.setMinimumSize(QtCore.QSize(9, 23))
        self.Overskriftkamera_4.setMaximumSize(QtCore.QSize(431, 23))
        self.Overskriftkamera_4.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.Overskriftkamera_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Overskriftkamera_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Overskriftkamera_4.setObjectName("Overskriftkamera_4")
        self.overskrifkamera_6 = QtWidgets.QLabel(self.Overskriftkamera_4)
        self.overskrifkamera_6.setGeometry(QtCore.QRect(0, 0, 421, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overskrifkamera_6.sizePolicy().hasHeightForWidth())
        self.overskrifkamera_6.setSizePolicy(sizePolicy)
        self.overskrifkamera_6.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.overskrifkamera_6.setObjectName("overskrifkamera_6")
        self.column3Layout.addWidget(self.Overskriftkamera_4)
        self.kameraBtnFrame = QtWidgets.QFrame(self.column3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.kameraBtnFrame.sizePolicy().hasHeightForWidth())
        self.kameraBtnFrame.setSizePolicy(sizePolicy)
        self.kameraBtnFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.kameraBtnFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.kameraBtnFrame.setObjectName("kameraBtnFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.kameraBtnFrame)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_5 = QtWidgets.QFrame(self.kameraBtnFrame)
        self.frame_5.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_14.addLayout(self.verticalLayout_29)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_25 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(0, 47))
        self.label_25.setMaximumSize(QtCore.QSize(311, 16777215))
        self.label_25.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_8.addWidget(self.label_25)
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 47))
        self.label_23.setMaximumSize(QtCore.QSize(311, 16777215))
        self.label_23.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_8.addWidget(self.label_23)
        self.label = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 47))
        self.label.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 47))
        self.label_24.setMaximumSize(QtCore.QSize(311, 16777215))
        self.label_24.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_8.addWidget(self.label_24)
        self.label_26 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 47))
        self.label_26.setMaximumSize(QtCore.QSize(311, 16777215))
        self.label_26.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_8.addWidget(self.label_26)
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(0, 47))
        self.label_22.setMaximumSize(QtCore.QSize(311, 16777215))
        self.label_22.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.horizontalLayout_14.addLayout(self.verticalLayout_8)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.labelManipulatorSikring = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelManipulatorSikring.sizePolicy().hasHeightForWidth())
        self.labelManipulatorSikring.setSizePolicy(sizePolicy)
        self.labelManipulatorSikring.setMinimumSize(QtCore.QSize(311, 47))
        self.labelManipulatorSikring.setMaximumSize(QtCore.QSize(0, 50))
        self.labelManipulatorSikring.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.labelManipulatorSikring.setText("")
        self.labelManipulatorSikring.setObjectName("labelManipulatorSikring")
        self.verticalLayout_30.addWidget(self.labelManipulatorSikring)
        self.labelThrusterSikring = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelThrusterSikring.sizePolicy().hasHeightForWidth())
        self.labelThrusterSikring.setSizePolicy(sizePolicy)
        self.labelThrusterSikring.setMinimumSize(QtCore.QSize(0, 47))
        self.labelThrusterSikring.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.labelThrusterSikring.setText("")
        self.labelThrusterSikring.setObjectName("labelThrusterSikring")
        self.verticalLayout_30.addWidget(self.labelThrusterSikring)
        self.labelLekkasjeAlarm = QtWidgets.QLabel(self.frame_5)
        self.labelLekkasjeAlarm.setMinimumSize(QtCore.QSize(0, 47))
        self.labelLekkasjeAlarm.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.labelLekkasjeAlarm.setText("")
        self.labelLekkasjeAlarm.setObjectName("labelLekkasjeAlarm")
        self.verticalLayout_30.addWidget(self.labelLekkasjeAlarm)
        self.labelIMUAlarm = QtWidgets.QLabel(self.frame_5)
        self.labelIMUAlarm.setMinimumSize(QtCore.QSize(0, 47))
        self.labelIMUAlarm.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.labelIMUAlarm.setText("")
        self.labelIMUAlarm.setObjectName("labelIMUAlarm")
        self.verticalLayout_30.addWidget(self.labelIMUAlarm)
        self.labelTempAlarm = QtWidgets.QLabel(self.frame_5)
        self.labelTempAlarm.setMinimumSize(QtCore.QSize(0, 47))
        self.labelTempAlarm.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.labelTempAlarm.setText("")
        self.labelTempAlarm.setObjectName("labelTempAlarm")
        self.verticalLayout_30.addWidget(self.labelTempAlarm)
        self.labelTrykkAlarm = QtWidgets.QLabel(self.frame_5)
        self.labelTrykkAlarm.setMinimumSize(QtCore.QSize(0, 47))
        self.labelTrykkAlarm.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.labelTrykkAlarm.setText("")
        self.labelTrykkAlarm.setObjectName("labelTrykkAlarm")
        self.verticalLayout_30.addWidget(self.labelTrykkAlarm)
        self.horizontalLayout_14.addLayout(self.verticalLayout_30)
        self.verticalLayout_28.addLayout(self.horizontalLayout_14)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.column3Layout.addWidget(self.kameraBtnFrame)
        self.videooptakFrame = QtWidgets.QFrame(self.column3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videooptakFrame.sizePolicy().hasHeightForWidth())
        self.videooptakFrame.setSizePolicy(sizePolicy)
        self.videooptakFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.videooptakFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.videooptakFrame.setObjectName("videooptakFrame")
        self.kameraGrid = QtWidgets.QGridLayout(self.videooptakFrame)
        self.kameraGrid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.kameraGrid.setSpacing(5)
        self.kameraGrid.setObjectName("kameraGrid")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btnResetThruster = QtWidgets.QPushButton(self.videooptakFrame)
        self.btnResetThruster.setObjectName("btnResetThruster")
        self.horizontalLayout_18.addWidget(self.btnResetThruster)
        self.btnResetManipulator = QtWidgets.QPushButton(self.videooptakFrame)
        self.btnResetManipulator.setObjectName("btnResetManipulator")
        self.horizontalLayout_18.addWidget(self.btnResetManipulator)
        self.kameraGrid.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.title_start_videoopptak = QtWidgets.QLabel(self.videooptakFrame)
        self.title_start_videoopptak.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_start_videoopptak.setFont(font)
        self.title_start_videoopptak.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.title_start_videoopptak.setObjectName("title_start_videoopptak")
        self.kameraGrid.addWidget(self.title_start_videoopptak, 0, 0, 1, 1)
        self.title_start_videoopptak_2 = QtWidgets.QLabel(self.videooptakFrame)
        self.title_start_videoopptak_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_start_videoopptak_2.setFont(font)
        self.title_start_videoopptak_2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.title_start_videoopptak_2.setObjectName("title_start_videoopptak_2")
        self.kameraGrid.addWidget(self.title_start_videoopptak_2, 2, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.btnTopLys = QtWidgets.QPushButton(self.videooptakFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTopLys.sizePolicy().hasHeightForWidth())
        self.btnTopLys.setSizePolicy(sizePolicy)
        self.btnTopLys.setObjectName("btnTopLys")
        self.verticalLayout_21.addWidget(self.btnTopLys)
        self.slider_lys_forward = QtWidgets.QSlider(self.videooptakFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_lys_forward.sizePolicy().hasHeightForWidth())
        self.slider_lys_forward.setSizePolicy(sizePolicy)
        self.slider_lys_forward.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QSlider {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #009BFF, stop: 1 #003BFF); /* Blue gradient */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 20px;\n"
"    background: #FFFFFF;\n"
"    border: 2px solid #6E6976;\n"
"    margin: -5px 0px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #2E2A33;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #009BFF, stop: 1 #003BFF); /* Blue gradient */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #2E2A33;\n"
"    border-radius: 5px;\n"
"}")
        self.slider_lys_forward.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_lys_forward.setObjectName("slider_lys_forward")
        self.verticalLayout_21.addWidget(self.slider_lys_forward)
        self.horizontalLayout_19.addLayout(self.verticalLayout_21)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.btnBunnLys = QtWidgets.QPushButton(self.videooptakFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBunnLys.sizePolicy().hasHeightForWidth())
        self.btnBunnLys.setSizePolicy(sizePolicy)
        self.btnBunnLys.setObjectName("btnBunnLys")
        self.verticalLayout_23.addWidget(self.btnBunnLys)
        self.slider_lys_down = QtWidgets.QSlider(self.videooptakFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_lys_down.sizePolicy().hasHeightForWidth())
        self.slider_lys_down.setSizePolicy(sizePolicy)
        self.slider_lys_down.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QSlider {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #009BFF, stop: 1 #003BFF); /* Blue gradient */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 20px;\n"
"    background: #FFFFFF;\n"
"    border: 2px solid #6E6976;\n"
"    margin: -5px 0px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #2E2A33;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #009BFF, stop: 1 #003BFF); /* Blue gradient */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #2E2A33;\n"
"    border-radius: 5px;\n"
"}")
        self.slider_lys_down.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_lys_down.setObjectName("slider_lys_down")
        self.verticalLayout_23.addWidget(self.slider_lys_down)
        self.horizontalLayout_19.addLayout(self.verticalLayout_23)
        self.kameraGrid.addLayout(self.horizontalLayout_19, 3, 0, 1, 1)
        self.column3Layout.addWidget(self.videooptakFrame)
        self.horizontalLayout_6.addWidget(self.column3)
        self.column2 = QtWidgets.QFrame(self.row)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.column2.sizePolicy().hasHeightForWidth())
        self.column2.setSizePolicy(sizePolicy)
        self.column2.setMinimumSize(QtCore.QSize(400, 0))
        self.column2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.column2.setFont(font)
        self.column2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.column2.setObjectName("column2")
        self.column2Layout = QtWidgets.QVBoxLayout(self.column2)
        self.column2Layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.column2Layout.setSpacing(5)
        self.column2Layout.setObjectName("column2Layout")
        self.title_motor = QtWidgets.QLabel(self.column2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_motor.setFont(font)
        self.title_motor.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.title_motor.setObjectName("title_motor")
        self.column2Layout.addWidget(self.title_motor)
        self.motorOuterContainer = QtWidgets.QFrame(self.column2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motorOuterContainer.sizePolicy().hasHeightForWidth())
        self.motorOuterContainer.setSizePolicy(sizePolicy)
        self.motorOuterContainer.setMinimumSize(QtCore.QSize(0, 350))
        self.motorOuterContainer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.motorOuterContainer.setStyleSheet("")
        self.motorOuterContainer.setObjectName("motorOuterContainer")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.motorOuterContainer)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_22 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_15.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_15.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_15.addWidget(self.pushButton_24)
        self.pushButton_11 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_15.addWidget(self.pushButton_11)
        self.pushButton_15 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_15.addWidget(self.pushButton_15)
        self.pushButton_17 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_15.addWidget(self.pushButton_17)
        self.pushButton_12 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_15.addWidget(self.pushButton_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_14 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_15.addWidget(self.pushButton_14)
        self.pushButton_16 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_15.addWidget(self.pushButton_16)
        self.pushButton_18 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_15.addWidget(self.pushButton_18)
        self.pushButton_13 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_15.addWidget(self.pushButton_13)
        self.verticalLayout_34.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_10 = QtWidgets.QLabel(self.motorOuterContainer)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_10.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_37.addWidget(self.label_10)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_37.addItem(spacerItem)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_4.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_4.setSizePolicy(sizePolicy)
        self.horizontalSlider_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalSlider_4.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QSlider {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #009BFF, stop: 1 #003BFF); /* Blue gradient */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 20px;\n"
"    background: #FFFFFF;\n"
"    border: 2px solid #6E6976;\n"
"    margin: -5px 0px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #2E2A33;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #009BFF, stop: 1 #003BFF); /* Blue gradient */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #2E2A33;\n"
"    border-radius: 5px;\n"
"}")
        self.horizontalSlider_4.setMaximum(180)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.verticalLayout_37.addWidget(self.horizontalSlider_4)
        self.label_9 = QtWidgets.QLabel(self.motorOuterContainer)
        self.label_9.setMaximumSize(QtCore.QSize(100, 25))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_37.addWidget(self.label_9)
        self.horizontalLayout_17.addLayout(self.verticalLayout_37)
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        spacerItem1 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_41.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.motorOuterContainer)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_41.addWidget(self.label_8)
        self.pushButton_20 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_41.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_41.addWidget(self.pushButton_21)
        self.horizontalLayout_17.addLayout(self.verticalLayout_41)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_11 = QtWidgets.QLabel(self.motorOuterContainer)
        self.label_11.setMinimumSize(QtCore.QSize(1, 20))
        self.label_11.setMaximumSize(QtCore.QSize(90, 25))
        self.label_11.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #1E90FF;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_40.addWidget(self.label_11)
        self.reguleringDropdown = QtWidgets.QComboBox(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reguleringDropdown.sizePolicy().hasHeightForWidth())
        self.reguleringDropdown.setSizePolicy(sizePolicy)
        self.reguleringDropdown.setMinimumSize(QtCore.QSize(92, 0))
        self.reguleringDropdown.setStyleSheet("QComboBox {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    width: 20px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #6E6976;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    color: #FFFFFF;\n"
"}")
        self.reguleringDropdown.setObjectName("reguleringDropdown")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.verticalLayout_40.addWidget(self.reguleringDropdown)
        self.tuningInput_2 = QtWidgets.QLineEdit(self.motorOuterContainer)
        self.tuningInput_2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.tuningInput_2.setObjectName("tuningInput_2")
        self.verticalLayout_40.addWidget(self.tuningInput_2)
        self.btnRegTuning = QtWidgets.QPushButton(self.motorOuterContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRegTuning.sizePolicy().hasHeightForWidth())
        self.btnRegTuning.setSizePolicy(sizePolicy)
        self.btnRegTuning.setMinimumSize(QtCore.QSize(260, 0))
        self.btnRegTuning.setObjectName("btnRegTuning")
        self.verticalLayout_40.addWidget(self.btnRegTuning)
        self.horizontalLayout_17.addLayout(self.verticalLayout_40)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.verticalLayout_34.addLayout(self.horizontalLayout_16)
        self.verticalLayout_16.addLayout(self.verticalLayout_34)
        self.horizontalLayout_2.addLayout(self.verticalLayout_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.column2Layout.addWidget(self.motorOuterContainer)
        self.maniOuterContainer = QtWidgets.QFrame(self.column2)
        self.maniOuterContainer.setMinimumSize(QtCore.QSize(360, 180))
        self.maniOuterContainer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.maniOuterContainer.setObjectName("maniOuterContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.maniOuterContainer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.maniOuterContainer)
        self.label_5.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.horizontalLayout_10.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.maniOuterContainer)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.maniOuterContainer)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_12.addWidget(self.label_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.column2Layout.addWidget(self.maniOuterContainer)
        self.horizontalLayout_6.addWidget(self.column2)
        self.verticalLayout.addWidget(self.row, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout_4.addWidget(self.pagesContainer)
        self.verticalLayout_6.addWidget(self.content)
        self.bottomBar = QtWidgets.QFrame(self.contentBottom)
        self.bottomBar.setMinimumSize(QtCore.QSize(0, 22))
        self.bottomBar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.bottomBar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.bottomBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bottomBar.setObjectName("bottomBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bottomBar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.version = QtWidgets.QLabel(self.bottomBar)
        self.version.setText("")
        self.version.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.version.setObjectName("version")
        self.horizontalLayout_5.addWidget(self.version)
        self.frame_size_grip = QtWidgets.QFrame(self.bottomBar)
        self.frame_size_grip.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_size_grip.setStyleSheet("")
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.grip_icon = QtWidgets.QLabel(self.frame_size_grip)
        self.grip_icon.setGeometry(QtCore.QRect(-15, 0, 40, 20))
        self.grip_icon.setText("")
        self.grip_icon.setPixmap(QtGui.QPixmap(":/icons/images/icons/cil-size-grip.png"))
        self.grip_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.grip_icon.setObjectName("grip_icon")
        self.horizontalLayout_5.addWidget(self.frame_size_grip)
        self.verticalLayout_6.addWidget(self.bottomBar)
        self.verticalLayout_2.addWidget(self.contentBottom)
        self.appLayout.addWidget(self.contentBox)
        self.verticalLayout_14.addWidget(self.bgApp)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_kjoremodus.setText(_translate("MainWindow", "Thrusterpådrag"))
        self.labelVVF_3.setText(_translate("MainWindow", "------"))
        self.labelVHF_3.setText(_translate("MainWindow", "------"))
        self.labelHHF_3.setText(_translate("MainWindow", "------"))
        self.labelHHB_3.setText(_translate("MainWindow", "------"))
        self.labelVHB_3.setText(_translate("MainWindow", "------"))
        self.labelVVB_3.setText(_translate("MainWindow", "------"))
        self.labelHVB_3.setText(_translate("MainWindow", "------"))
        self.labelHVF_3.setText(_translate("MainWindow", "------"))
        self.title_kjoremodus_2.setText(_translate("MainWindow", "Temperatur"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Høyre :<br/><br/>Venstre :<br/><br/>Vann :</p><p>Sensorkort :</p></body></html>"))
        self.overskrifkamera_6.setText(_translate("MainWindow", "Alarm Navn                                                                              Feilkode                                           "))
        self.label_25.setText(_translate("MainWindow", "Høyre side"))
        self.label_23.setText(_translate("MainWindow", "Venstre side"))
        self.label.setText(_translate("MainWindow", "Lekkasje"))
        self.label_24.setText(_translate("MainWindow", "IMU"))
        self.label_26.setText(_translate("MainWindow", "Temp"))
        self.label_22.setText(_translate("MainWindow", "Trykk"))
        self.btnResetThruster.setText(_translate("MainWindow", "Venstre side"))
        self.btnResetManipulator.setText(_translate("MainWindow", "Høyre Side"))
        self.title_start_videoopptak.setText(_translate("MainWindow", "Reset Sikringer"))
        self.title_start_videoopptak.setProperty("colorStyle", _translate("MainWindow", "subTitle"))
        self.title_start_videoopptak_2.setText(_translate("MainWindow", "Lys Oppe                                                          Lys Nede"))
        self.title_start_videoopptak_2.setProperty("colorStyle", _translate("MainWindow", "subTitle"))
        self.btnTopLys.setText(_translate("MainWindow", "På/Av"))
        self.btnBunnLys.setText(_translate("MainWindow", "På/Av"))
        self.title_motor.setText(_translate("MainWindow", "Kamerafunksjoner                                    Regulering"))
        self.pushButton_22.setText(_translate("MainWindow", "Manuell Kjøring"))
        self.pushButton_23.setText(_translate("MainWindow", "Autonom Docking"))
        self.pushButton_24.setText(_translate("MainWindow", "Start Frog Count"))
        self.pushButton_11.setText(_translate("MainWindow", "Åpne Kamera"))
        self.pushButton_15.setText(_translate("MainWindow", "Skjermbilde"))
        self.pushButton_17.setText(_translate("MainWindow", "Vis Bilder"))
        self.pushButton_12.setText(_translate("MainWindow", "Ta opp Video"))
        self.pushButton_14.setText(_translate("MainWindow", "Dybde Regulering"))
        self.pushButton_16.setText(_translate("MainWindow", "Stamp Regulering"))
        self.pushButton_18.setText(_translate("MainWindow", "Rull Regulering"))
        self.pushButton_13.setText(_translate("MainWindow", "All Regulering"))
        self.label_10.setText(_translate("MainWindow", "Endre Kameravinkel"))
        self.label_9.setText(_translate("MainWindow", "Kameravinkel"))
        self.label_8.setText(_translate("MainWindow", "Reset Sikringar"))
        self.pushButton_20.setText(_translate("MainWindow", "Reset Høgre Side"))
        self.pushButton_21.setText(_translate("MainWindow", "Reset Venstre Side"))
        self.label_11.setText(_translate("MainWindow", "Regulator Tuning"))
        self.reguleringDropdown.setItemText(0, _translate("MainWindow", "Rull KI"))
        self.reguleringDropdown.setItemText(1, _translate("MainWindow", "Rull KD"))
        self.reguleringDropdown.setItemText(2, _translate("MainWindow", "Rull KP"))
        self.reguleringDropdown.setItemText(3, _translate("MainWindow", "Stamp KI"))
        self.reguleringDropdown.setItemText(4, _translate("MainWindow", "Stamp KD"))
        self.reguleringDropdown.setItemText(5, _translate("MainWindow", "Stamp KP"))
        self.reguleringDropdown.setItemText(6, _translate("MainWindow", "Dybde KI"))
        self.reguleringDropdown.setItemText(7, _translate("MainWindow", "Dybde KD"))
        self.reguleringDropdown.setItemText(8, _translate("MainWindow", "Dybde KP"))
        self.reguleringDropdown.setItemText(9, _translate("MainWindow", "TS"))
        self.reguleringDropdown.setItemText(10, _translate("MainWindow", "Alpha"))
        self.tuningInput_2.setText(_translate("MainWindow", "Skriv inn verdi:"))
        self.btnRegTuning.setText(_translate("MainWindow", "Submit"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Høyre :<br/><br/><br/>Venstre :</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
