# Form implementation generated from reading ui file 'd:\Bachelor_GUI\gui\testing2.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.482955, y1:1, x2:0.489, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(4, 38, 53, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main.setObjectName("main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left = QtWidgets.QFrame(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left.sizePolicy().hasHeightForWidth())
        self.left.setSizePolicy(sizePolicy)
        self.left.setMaximumSize(QtCore.QSize(317, 16777215))
        self.left.setStyleSheet("background-color:none;")
        self.left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.left.setObjectName("left")
        self.Kjoremodus = QtWidgets.QFrame(self.left)
        self.Kjoremodus.setGeometry(QtCore.QRect(10, 30, 151, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Kjoremodus.sizePolicy().hasHeightForWidth())
        self.Kjoremodus.setSizePolicy(sizePolicy)
        self.Kjoremodus.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.Kjoremodus.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Kjoremodus.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Kjoremodus.setObjectName("Kjoremodus")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Kjoremodus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAutonom = QtWidgets.QPushButton(self.Kjoremodus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAutonom.sizePolicy().hasHeightForWidth())
        self.btnAutonom.setSizePolicy(sizePolicy)
        self.btnAutonom.setObjectName("btnAutonom")
        self.verticalLayout.addWidget(self.btnAutonom)
        self.btnFrogCount = QtWidgets.QPushButton(self.Kjoremodus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFrogCount.sizePolicy().hasHeightForWidth())
        self.btnFrogCount.setSizePolicy(sizePolicy)
        self.btnFrogCount.setObjectName("btnFrogCount")
        self.verticalLayout.addWidget(self.btnFrogCount)
        self.btnManuell = QtWidgets.QPushButton(self.Kjoremodus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnManuell.sizePolicy().hasHeightForWidth())
        self.btnManuell.setSizePolicy(sizePolicy)
        self.btnManuell.setObjectName("btnManuell")
        self.verticalLayout.addWidget(self.btnManuell)
        self.camera = QtWidgets.QFrame(self.left)
        self.camera.setGeometry(QtCore.QRect(163, 30, 151, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera.sizePolicy().hasHeightForWidth())
        self.camera.setSizePolicy(sizePolicy)
        self.camera.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.camera.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.camera.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.camera.setObjectName("camera")
        self.gridLayout = QtWidgets.QGridLayout(self.camera)
        self.gridLayout.setObjectName("gridLayout")
        self.btnOpenCamera = QtWidgets.QPushButton(self.camera)
        self.btnOpenCamera.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenCamera.sizePolicy().hasHeightForWidth())
        self.btnOpenCamera.setSizePolicy(sizePolicy)
        self.btnOpenCamera.setObjectName("btnOpenCamera")
        self.gridLayout.addWidget(self.btnOpenCamera, 0, 0, 1, 1)
        self.btnTakePic = QtWidgets.QPushButton(self.camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTakePic.sizePolicy().hasHeightForWidth())
        self.btnTakePic.setSizePolicy(sizePolicy)
        self.btnTakePic.setObjectName("btnTakePic")
        self.gridLayout.addWidget(self.btnTakePic, 1, 0, 1, 1)
        self.btnRecord = QtWidgets.QPushButton(self.camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRecord.sizePolicy().hasHeightForWidth())
        self.btnRecord.setSizePolicy(sizePolicy)
        self.btnRecord.setObjectName("btnRecord")
        self.gridLayout.addWidget(self.btnRecord, 2, 0, 1, 1)
        self.showNewWindowButton = QtWidgets.QPushButton(self.camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showNewWindowButton.sizePolicy().hasHeightForWidth())
        self.showNewWindowButton.setSizePolicy(sizePolicy)
        self.showNewWindowButton.setObjectName("showNewWindowButton")
        self.gridLayout.addWidget(self.showNewWindowButton, 3, 0, 1, 1)
        self.overskriftKjoremodus = QtWidgets.QFrame(self.left)
        self.overskriftKjoremodus.setGeometry(QtCore.QRect(10, 1, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overskriftKjoremodus.sizePolicy().hasHeightForWidth())
        self.overskriftKjoremodus.setSizePolicy(sizePolicy)
        self.overskriftKjoremodus.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.overskriftKjoremodus.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.overskriftKjoremodus.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.overskriftKjoremodus.setObjectName("overskriftKjoremodus")
        self.label = QtWidgets.QLabel(self.overskriftKjoremodus)
        self.label.setGeometry(QtCore.QRect(0, 0, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.Overskriftkamera = QtWidgets.QFrame(self.left)
        self.Overskriftkamera.setGeometry(QtCore.QRect(160, 0, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Overskriftkamera.sizePolicy().hasHeightForWidth())
        self.Overskriftkamera.setSizePolicy(sizePolicy)
        self.Overskriftkamera.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.Overskriftkamera.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Overskriftkamera.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Overskriftkamera.setObjectName("Overskriftkamera")
        self.overskrifkamera = QtWidgets.QLabel(self.Overskriftkamera)
        self.overskrifkamera.setGeometry(QtCore.QRect(0, 0, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overskrifkamera.sizePolicy().hasHeightForWidth())
        self.overskrifkamera.setSizePolicy(sizePolicy)
        self.overskrifkamera.setObjectName("overskrifkamera")
        self.Overskriftkamera_2 = QtWidgets.QFrame(self.left)
        self.Overskriftkamera_2.setGeometry(QtCore.QRect(10, 250, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Overskriftkamera_2.sizePolicy().hasHeightForWidth())
        self.Overskriftkamera_2.setSizePolicy(sizePolicy)
        self.Overskriftkamera_2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.Overskriftkamera_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Overskriftkamera_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Overskriftkamera_2.setObjectName("Overskriftkamera_2")
        self.overskrifkamera_3 = QtWidgets.QLabel(self.Overskriftkamera_2)
        self.overskrifkamera_3.setGeometry(QtCore.QRect(0, 0, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overskrifkamera_3.sizePolicy().hasHeightForWidth())
        self.overskrifkamera_3.setSizePolicy(sizePolicy)
        self.overskrifkamera_3.setObjectName("overskrifkamera_3")
        self.Overskriftkamera_3 = QtWidgets.QFrame(self.left)
        self.Overskriftkamera_3.setGeometry(QtCore.QRect(170, 250, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Overskriftkamera_3.sizePolicy().hasHeightForWidth())
        self.Overskriftkamera_3.setSizePolicy(sizePolicy)
        self.Overskriftkamera_3.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.Overskriftkamera_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Overskriftkamera_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Overskriftkamera_3.setObjectName("Overskriftkamera_3")
        self.overskrifkamera_4 = QtWidgets.QLabel(self.Overskriftkamera_3)
        self.overskrifkamera_4.setGeometry(QtCore.QRect(0, 0, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overskrifkamera_4.sizePolicy().hasHeightForWidth())
        self.overskrifkamera_4.setSizePolicy(sizePolicy)
        self.overskrifkamera_4.setObjectName("overskrifkamera_4")
        self.frame_2 = QtWidgets.QFrame(self.left)
        self.frame_2.setGeometry(QtCore.QRect(10, 280, 151, 81))
        self.frame_2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_2)
        self.horizontalSlider.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QSlider {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #009BFF, stop: 1 #003BFF); /* Blue gradient */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 20px;\n"
"    background: #FFFFFF;\n"
"    border: 2px solid #6E6976;\n"
"    margin: -5px 0px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #2E2A33;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #009BFF, stop: 1 #003BFF); /* Blue gradient */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #2E2A33;\n"
"    border-radius: 5px;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_4.addWidget(self.horizontalSlider)
        self.frame_3 = QtWidgets.QFrame(self.left)
        self.frame_3.setGeometry(QtCore.QRect(160, 280, 151, 81))
        self.frame_3.setStyleSheet("QWidget {\n"
"background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"background-color: #2E2A33;\n"
"border: 2px solid #6E6976;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"background-color: #2E2A33;\n"
"border: 2px solid #6E6976;\n"
"border-radius: 10px;\n"
"color: #FFFFFF;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #6E6976;\n"
"color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"background-color: #2E2A33;\n"
"border: 2px solid #6E6976;\n"
"border-radius: 10px;\n"
"color: #FFFFFF;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"color: #FFFFFF;\n"
"}\n"
"\n"
"QSlider {\n"
"background-color: #2E2A33;\n"
"border: 2px solid #6E6976;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"height: 10px;\n"
"background: #6E6976;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 20px;\n"
"height: 20px;\n"
"background: #2196F3;\n"
"border: 2px solid #6E6976;\n"
"margin: -5px 0px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: #2E2A33;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: #2196F3;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #6E6976;\n"
"border-radius: 5px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_5.addWidget(self.pushButton_4)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QSlider {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #009BFF, stop: 1 #003BFF); /* Blue gradient */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 20px;\n"
"    background: #FFFFFF;\n"
"    border: 2px solid #6E6976;\n"
"    margin: -5px 0px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #2E2A33;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #009BFF, stop: 1 #003BFF); /* Blue gradient */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #2E2A33;\n"
"    border-radius: 5px;\n"
"}")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout_5.addWidget(self.horizontalSlider_2)
        self.horizontalLayout_2.addWidget(self.left)
        self.Middle = QtWidgets.QFrame(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Middle.sizePolicy().hasHeightForWidth())
        self.Middle.setSizePolicy(sizePolicy)
        self.Middle.setStyleSheet("background-color:none;")
        self.Middle.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Middle.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Middle.setObjectName("Middle")
        self.overskriftRegulering = QtWidgets.QFrame(self.Middle)
        self.overskriftRegulering.setGeometry(QtCore.QRect(0, 0, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overskriftRegulering.sizePolicy().hasHeightForWidth())
        self.overskriftRegulering.setSizePolicy(sizePolicy)
        self.overskriftRegulering.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.overskriftRegulering.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.overskriftRegulering.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.overskriftRegulering.setObjectName("overskriftRegulering")
        self.regulering = QtWidgets.QLabel(self.overskriftRegulering)
        self.regulering.setGeometry(QtCore.QRect(0, 0, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regulering.sizePolicy().hasHeightForWidth())
        self.regulering.setSizePolicy(sizePolicy)
        self.regulering.setObjectName("regulering")
        self.Kjoremodus_2 = QtWidgets.QFrame(self.Middle)
        self.Kjoremodus_2.setGeometry(QtCore.QRect(0, 30, 151, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Kjoremodus_2.sizePolicy().hasHeightForWidth())
        self.Kjoremodus_2.setSizePolicy(sizePolicy)
        self.Kjoremodus_2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.Kjoremodus_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Kjoremodus_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Kjoremodus_2.setObjectName("Kjoremodus_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Kjoremodus_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnAutonom_3 = QtWidgets.QPushButton(self.Kjoremodus_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAutonom_3.sizePolicy().hasHeightForWidth())
        self.btnAutonom_3.setSizePolicy(sizePolicy)
        self.btnAutonom_3.setObjectName("btnAutonom_3")
        self.verticalLayout_3.addWidget(self.btnAutonom_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.Kjoremodus_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.btnFrogCount_3 = QtWidgets.QPushButton(self.Kjoremodus_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFrogCount_3.sizePolicy().hasHeightForWidth())
        self.btnFrogCount_3.setSizePolicy(sizePolicy)
        self.btnFrogCount_3.setObjectName("btnFrogCount_3")
        self.verticalLayout_3.addWidget(self.btnFrogCount_3)
        self.btnManuell_3 = QtWidgets.QPushButton(self.Kjoremodus_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnManuell_3.sizePolicy().hasHeightForWidth())
        self.btnManuell_3.setSizePolicy(sizePolicy)
        self.btnManuell_3.setObjectName("btnManuell_3")
        self.verticalLayout_3.addWidget(self.btnManuell_3)
        self.camera_2 = QtWidgets.QFrame(self.Middle)
        self.camera_2.setGeometry(QtCore.QRect(150, 30, 161, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_2.sizePolicy().hasHeightForWidth())
        self.camera_2.setSizePolicy(sizePolicy)
        self.camera_2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.camera_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.camera_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.camera_2.setObjectName("camera_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.camera_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.camera_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.btnTakePic_2 = QtWidgets.QPushButton(self.camera_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTakePic_2.sizePolicy().hasHeightForWidth())
        self.btnTakePic_2.setSizePolicy(sizePolicy)
        self.btnTakePic_2.setObjectName("btnTakePic_2")
        self.gridLayout_2.addWidget(self.btnTakePic_2, 0, 0, 1, 1)
        self.btnRecord_2 = QtWidgets.QPushButton(self.camera_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRecord_2.sizePolicy().hasHeightForWidth())
        self.btnRecord_2.setSizePolicy(sizePolicy)
        self.btnRecord_2.setObjectName("btnRecord_2")
        self.gridLayout_2.addWidget(self.btnRecord_2, 2, 0, 1, 1)
        self.overskriftRegulering_2 = QtWidgets.QFrame(self.Middle)
        self.overskriftRegulering_2.setGeometry(QtCore.QRect(150, 0, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overskriftRegulering_2.sizePolicy().hasHeightForWidth())
        self.overskriftRegulering_2.setSizePolicy(sizePolicy)
        self.overskriftRegulering_2.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.overskriftRegulering_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.overskriftRegulering_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.overskriftRegulering_2.setObjectName("overskriftRegulering_2")
        self.regulering_2 = QtWidgets.QLabel(self.overskriftRegulering_2)
        self.regulering_2.setGeometry(QtCore.QRect(0, 0, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regulering_2.sizePolicy().hasHeightForWidth())
        self.regulering_2.setSizePolicy(sizePolicy)
        self.regulering_2.setObjectName("regulering_2")
        self.frame = QtWidgets.QFrame(self.Middle)
        self.frame.setGeometry(QtCore.QRect(0, 250, 311, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 311, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/rov/E:/image.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 50, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 180, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(0, 220, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(270, 10, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(230, 50, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(220, 180, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(280, 220, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.labelVVF = QtWidgets.QLabel(self.frame)
        self.labelVVF.setGeometry(QtCore.QRect(60, 10, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVVF.sizePolicy().hasHeightForWidth())
        self.labelVVF.setSizePolicy(sizePolicy)
        self.labelVVF.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"}")
        self.labelVVF.setObjectName("labelVVF")
        self.labelVHF = QtWidgets.QLabel(self.frame)
        self.labelVHF.setGeometry(QtCore.QRect(210, 10, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVHF.sizePolicy().hasHeightForWidth())
        self.labelVHF.setSizePolicy(sizePolicy)
        self.labelVHF.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"}")
        self.labelVHF.setObjectName("labelVHF")
        self.labelHHF = QtWidgets.QLabel(self.frame)
        self.labelHHF.setGeometry(QtCore.QRect(220, 70, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHHF.sizePolicy().hasHeightForWidth())
        self.labelHHF.setSizePolicy(sizePolicy)
        self.labelHHF.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"}")
        self.labelHHF.setObjectName("labelHHF")
        self.labelHHB = QtWidgets.QLabel(self.frame)
        self.labelHHB.setGeometry(QtCore.QRect(220, 140, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHHB.sizePolicy().hasHeightForWidth())
        self.labelHHB.setSizePolicy(sizePolicy)
        self.labelHHB.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"}")
        self.labelHHB.setObjectName("labelHHB")
        self.labelVHB = QtWidgets.QLabel(self.frame)
        self.labelVHB.setGeometry(QtCore.QRect(210, 210, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVHB.sizePolicy().hasHeightForWidth())
        self.labelVHB.setSizePolicy(sizePolicy)
        self.labelVHB.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"}")
        self.labelVHB.setObjectName("labelVHB")
        self.labelVVB = QtWidgets.QLabel(self.frame)
        self.labelVVB.setGeometry(QtCore.QRect(60, 210, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVVB.sizePolicy().hasHeightForWidth())
        self.labelVVB.setSizePolicy(sizePolicy)
        self.labelVVB.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"}")
        self.labelVVB.setObjectName("labelVVB")
        self.labelHVB = QtWidgets.QLabel(self.frame)
        self.labelHVB.setGeometry(QtCore.QRect(50, 140, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHVB.sizePolicy().hasHeightForWidth())
        self.labelHVB.setSizePolicy(sizePolicy)
        self.labelHVB.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"}")
        self.labelHVB.setObjectName("labelHVB")
        self.labelHVF = QtWidgets.QLabel(self.frame)
        self.labelHVF.setGeometry(QtCore.QRect(40, 70, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHVF.sizePolicy().hasHeightForWidth())
        self.labelHVF.setSizePolicy(sizePolicy)
        self.labelHVF.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid blue;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"}")
        self.labelHVF.setObjectName("labelHVF")
        self.horizontalLayout_2.addWidget(self.Middle)
        self.Right = QtWidgets.QFrame(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Right.sizePolicy().hasHeightForWidth())
        self.Right.setSizePolicy(sizePolicy)
        self.Right.setStyleSheet("background-color:none;")
        self.Right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Right.setObjectName("Right")
        self.horizontalLayout_2.addWidget(self.Right)
        self.horizontalLayout.addWidget(self.main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAutonom.setText(_translate("MainWindow", "Autonom Docking"))
        self.btnFrogCount.setText(_translate("MainWindow", "Start Frog Count"))
        self.btnManuell.setText(_translate("MainWindow", "Manuell Kjøring"))
        self.btnOpenCamera.setText(_translate("MainWindow", "Åpne Kamera"))
        self.btnTakePic.setText(_translate("MainWindow", "Skjermbilde"))
        self.btnRecord.setText(_translate("MainWindow", "Ta opp video"))
        self.showNewWindowButton.setText(_translate("MainWindow", "Vis Bilder"))
        self.label.setText(_translate("MainWindow", "Kjøremodus"))
        self.overskrifkamera.setText(_translate("MainWindow", "Kamera"))
        self.overskrifkamera_3.setText(_translate("MainWindow", "ToppLys"))
        self.overskrifkamera_4.setText(_translate("MainWindow", "Bunnlys"))
        self.pushButton_3.setText(_translate("MainWindow", "På/Av"))
        self.pushButton_4.setText(_translate("MainWindow", "På/Av"))
        self.regulering.setText(_translate("MainWindow", "Regulering"))
        self.btnAutonom_3.setText(_translate("MainWindow", "All Regulering"))
        self.pushButton_2.setText(_translate("MainWindow", "Rull Regulering"))
        self.btnFrogCount_3.setText(_translate("MainWindow", "Stamp Regulering"))
        self.btnManuell_3.setText(_translate("MainWindow", "Dybde Regulering "))
        self.pushButton.setText(_translate("MainWindow", "Reset høgre side"))
        self.btnTakePic_2.setText(_translate("MainWindow", "Reset 5V"))
        self.btnRecord_2.setText(_translate("MainWindow", "Reset venstre side"))
        self.regulering_2.setText(_translate("MainWindow", "Sikringer"))
        self.label_3.setText(_translate("MainWindow", "VVF"))
        self.label_4.setText(_translate("MainWindow", "HVF"))
        self.label_5.setText(_translate("MainWindow", "HVB"))
        self.label_6.setText(_translate("MainWindow", "VVB"))
        self.label_7.setText(_translate("MainWindow", "VHF"))
        self.label_8.setText(_translate("MainWindow", "HHF"))
        self.label_9.setText(_translate("MainWindow", "HHB"))
        self.label_10.setText(_translate("MainWindow", "VHB"))
        self.labelVVF.setText(_translate("MainWindow", "------"))
        self.labelVHF.setText(_translate("MainWindow", "------"))
        self.labelHHF.setText(_translate("MainWindow", "------"))
        self.labelHHB.setText(_translate("MainWindow", "------"))
        self.labelVHB.setText(_translate("MainWindow", "------"))
        self.labelVVB.setText(_translate("MainWindow", "------"))
        self.labelHVB.setText(_translate("MainWindow", "------"))
        self.labelHVF.setText(_translate("MainWindow", "------"))
