# Form implementation generated from reading ui file 'd:\Bachelor_GUI\gui\SubseaTest.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(889, 820)
        Form.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    color: #aaa;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    \n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(110, 105, 118, 255),stop:1 rgba(57, 49, 68, 255));\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background-color: #444;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    border: 1px solid #000;\n"
"    background-color: #444;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #444;\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    padding-right: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #55aaff;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolBar\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"    border: 1px solid #222;\n"
"    background-color: #333;\n"
"    color: #aaa;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(75, 165, 255, 255),stop:0.509615 rgba(119, 187, 255, 255),stop:1 rgba(72, 164, 255, 255));\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    margin-right: 2px;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(65, 155, 245, 255),stop:0.509615 rgba(109, 177, 245, 255),stop:1 rgba(72, 164, 255, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #9999ff;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit{\n"
"    background-color: #fff;\n"
"    color: #000;\n"
"    selection-color: #fff;\n"
"    selection-background-color: #507098;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"QTreeView\n"
"{\n"
"    background-color: #242526;\n"
"       show-decoration-selected: 0;\n"
"       selection-background-color: transparent; /* Used on Mac */\n"
"    alternate-background-color: #404040;\n"
"    selection-color: #fff; /* Used on Mac */\n"
"    font: 8pt;\n"
"    color: #fff;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"QTreeView::item\n"
"{\n"
"    border-top-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:hover\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    show-decoration-selected: 1;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    background-color: #41cd52;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:!active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-closed.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-open.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal \n"
"{\n"
"    background-color: #333;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal \n"
"{\n"
"    width: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    background-color: #333;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical \n"
"{\n"
"    height: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"")
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setEnabled(True)
        self.btn1.setGeometry(QtCore.QRect(10, 60, 541, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn1.sizePolicy().hasHeightForWidth())
        self.btn1.setSizePolicy(sizePolicy)
        self.btn1.setMinimumSize(QtCore.QSize(0, 0))
        self.btn1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn1.setFont(font)
        self.btn1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn1.setCheckable(False)
        self.btn1.setChecked(False)
        self.btn1.setAutoRepeat(False)
        self.btn1.setObjectName("btn1")
        self.btn_autonom_docking = QtWidgets.QPushButton(Form)
        self.btn_autonom_docking.setGeometry(QtCore.QRect(10, 110, 541, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_autonom_docking.sizePolicy().hasHeightForWidth())
        self.btn_autonom_docking.setSizePolicy(sizePolicy)
        self.btn_autonom_docking.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_autonom_docking.setFont(font)
        self.btn_autonom_docking.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_autonom_docking.setObjectName("btn_autonom_docking")
        self.start_transect = QtWidgets.QPushButton(Form)
        self.start_transect.setGeometry(QtCore.QRect(10, 160, 541, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_transect.sizePolicy().hasHeightForWidth())
        self.start_transect.setSizePolicy(sizePolicy)
        self.start_transect.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start_transect.setFont(font)
        self.start_transect.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.start_transect.setObjectName("start_transect")
        self.title_effektforbruk = QtWidgets.QLabel(Form)
        self.title_effektforbruk.setGeometry(QtCore.QRect(20, 220, 191, 18))
        self.title_effektforbruk.setMinimumSize(QtCore.QSize(0, 0))
        self.title_effektforbruk.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_effektforbruk.setFont(font)
        self.title_effektforbruk.setStyleSheet("")
        self.title_effektforbruk.setObjectName("title_effektforbruk")
        self.text_effekt_elektronikk = QtWidgets.QLabel(Form)
        self.text_effekt_elektronikk.setGeometry(QtCore.QRect(20, 240, 113, 42))
        self.text_effekt_elektronikk.setMinimumSize(QtCore.QSize(0, 0))
        self.text_effekt_elektronikk.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_effekt_elektronikk.setFont(font)
        self.text_effekt_elektronikk.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_effekt_elektronikk.setObjectName("text_effekt_elektronikk")
        self.text_effekt_thrustere = QtWidgets.QLabel(Form)
        self.text_effekt_thrustere.setGeometry(QtCore.QRect(20, 280, 113, 42))
        self.text_effekt_thrustere.setMinimumSize(QtCore.QSize(0, 0))
        self.text_effekt_thrustere.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_effekt_thrustere.setFont(font)
        self.text_effekt_thrustere.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.text_effekt_thrustere.setObjectName("text_effekt_thrustere")
        self.text_effekt_manipulator = QtWidgets.QLabel(Form)
        self.text_effekt_manipulator.setGeometry(QtCore.QRect(20, 320, 113, 42))
        self.text_effekt_manipulator.setMinimumSize(QtCore.QSize(0, 0))
        self.text_effekt_manipulator.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_effekt_manipulator.setFont(font)
        self.text_effekt_manipulator.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_effekt_manipulator.setObjectName("text_effekt_manipulator")
        self.label_effekt_elektronikk = QtWidgets.QLabel(Form)
        self.label_effekt_elektronikk.setGeometry(QtCore.QRect(140, 240, 74, 42))
        self.label_effekt_elektronikk.setMinimumSize(QtCore.QSize(0, 0))
        self.label_effekt_elektronikk.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_effekt_elektronikk.setFont(font)
        self.label_effekt_elektronikk.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_effekt_elektronikk.setLineWidth(0)
        self.label_effekt_elektronikk.setMidLineWidth(0)
        self.label_effekt_elektronikk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_effekt_elektronikk.setObjectName("label_effekt_elektronikk")
        self.label_effekt_thrustere = QtWidgets.QLabel(Form)
        self.label_effekt_thrustere.setGeometry(QtCore.QRect(140, 280, 74, 42))
        self.label_effekt_thrustere.setMinimumSize(QtCore.QSize(0, 0))
        self.label_effekt_thrustere.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_effekt_thrustere.setFont(font)
        self.label_effekt_thrustere.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_effekt_thrustere.setLineWidth(0)
        self.label_effekt_thrustere.setMidLineWidth(0)
        self.label_effekt_thrustere.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_effekt_thrustere.setObjectName("label_effekt_thrustere")
        self.label_effekt_manipulator = QtWidgets.QLabel(Form)
        self.label_effekt_manipulator.setGeometry(QtCore.QRect(140, 320, 74, 42))
        self.label_effekt_manipulator.setMinimumSize(QtCore.QSize(0, 0))
        self.label_effekt_manipulator.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_effekt_manipulator.setFont(font)
        self.label_effekt_manipulator.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_effekt_manipulator.setLineWidth(0)
        self.label_effekt_manipulator.setMidLineWidth(0)
        self.label_effekt_manipulator.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_effekt_manipulator.setObjectName("label_effekt_manipulator")
        self.title_temp_ROV = QtWidgets.QLabel(Form)
        self.title_temp_ROV.setGeometry(QtCore.QRect(20, 380, 171, 18))
        self.title_temp_ROV.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_temp_ROV.setFont(font)
        self.title_temp_ROV.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.title_temp_ROV.setObjectName("title_temp_ROV")
        self.text_hovedkort = QtWidgets.QLabel(Form)
        self.text_hovedkort.setGeometry(QtCore.QRect(20, 400, 113, 38))
        self.text_hovedkort.setMinimumSize(QtCore.QSize(0, 0))
        self.text_hovedkort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_hovedkort.setFont(font)
        self.text_hovedkort.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.text_hovedkort.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.text_hovedkort.setObjectName("text_hovedkort")
        self.label_temp_ROV_hovedkort = QtWidgets.QLabel(Form)
        self.label_temp_ROV_hovedkort.setGeometry(QtCore.QRect(140, 400, 74, 38))
        self.label_temp_ROV_hovedkort.setMinimumSize(QtCore.QSize(0, 0))
        self.label_temp_ROV_hovedkort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_temp_ROV_hovedkort.setFont(font)
        self.label_temp_ROV_hovedkort.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_temp_ROV_hovedkort.setLineWidth(0)
        self.label_temp_ROV_hovedkort.setMidLineWidth(0)
        self.label_temp_ROV_hovedkort.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_temp_ROV_hovedkort.setObjectName("label_temp_ROV_hovedkort")
        self.text_kraftkort = QtWidgets.QLabel(Form)
        self.text_kraftkort.setGeometry(QtCore.QRect(20, 440, 113, 38))
        self.text_kraftkort.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_kraftkort.setFont(font)
        self.text_kraftkort.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_kraftkort.setObjectName("text_kraftkort")
        self.text_sensorkort = QtWidgets.QLabel(Form)
        self.text_sensorkort.setGeometry(QtCore.QRect(20, 480, 113, 38))
        self.text_sensorkort.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_sensorkort.setFont(font)
        self.text_sensorkort.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_sensorkort.setObjectName("text_sensorkort")
        self.label_temp_ROV_kraftkort = QtWidgets.QLabel(Form)
        self.label_temp_ROV_kraftkort.setGeometry(QtCore.QRect(140, 440, 74, 38))
        self.label_temp_ROV_kraftkort.setMinimumSize(QtCore.QSize(0, 0))
        self.label_temp_ROV_kraftkort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_temp_ROV_kraftkort.setFont(font)
        self.label_temp_ROV_kraftkort.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_temp_ROV_kraftkort.setLineWidth(0)
        self.label_temp_ROV_kraftkort.setMidLineWidth(0)
        self.label_temp_ROV_kraftkort.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_temp_ROV_kraftkort.setObjectName("label_temp_ROV_kraftkort")
        self.label_temp_ROV_sensorkort = QtWidgets.QLabel(Form)
        self.label_temp_ROV_sensorkort.setGeometry(QtCore.QRect(140, 480, 74, 38))
        self.label_temp_ROV_sensorkort.setMinimumSize(QtCore.QSize(0, 0))
        self.label_temp_ROV_sensorkort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_temp_ROV_sensorkort.setFont(font)
        self.label_temp_ROV_sensorkort.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_temp_ROV_sensorkort.setLineWidth(0)
        self.label_temp_ROV_sensorkort.setMidLineWidth(0)
        self.label_temp_ROV_sensorkort.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_temp_ROV_sensorkort.setObjectName("label_temp_ROV_sensorkort")
        self.title_motor = QtWidgets.QLabel(Form)
        self.title_motor.setGeometry(QtCore.QRect(220, 220, 421, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_motor.setFont(font)
        self.title_motor.setObjectName("title_motor")
        self.text_rov = QtWidgets.QLabel(Form)
        self.text_rov.setGeometry(QtCore.QRect(220, 240, 357, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_rov.setFont(font)
        self.text_rov.setStyleSheet("color: rgb(113, 126, 149);")
        self.text_rov.setLineWidth(1)
        self.text_rov.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.text_rov.setObjectName("text_rov")
        self.title_kjoremodus = QtWidgets.QLabel(Form)
        self.title_kjoremodus.setGeometry(QtCore.QRect(20, 10, 371, 46))
        self.title_kjoremodus.setMinimumSize(QtCore.QSize(0, 0))
        self.title_kjoremodus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_kjoremodus.setFont(font)
        self.title_kjoremodus.setStyleSheet("")
        self.title_kjoremodus.setObjectName("title_kjoremodus")
        self.lys_title = QtWidgets.QLabel(Form)
        self.lys_title.setGeometry(QtCore.QRect(220, 400, 123, 18))
        self.lys_title.setMinimumSize(QtCore.QSize(0, 0))
        self.lys_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lys_title.setFont(font)
        self.lys_title.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.lys_title.setObjectName("lys_title")
        self.text_lys_forward = QtWidgets.QLabel(Form)
        self.text_lys_forward.setGeometry(QtCore.QRect(230, 420, 123, 68))
        self.text_lys_forward.setMinimumSize(QtCore.QSize(0, 0))
        self.text_lys_forward.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_lys_forward.setFont(font)
        self.text_lys_forward.setStyleSheet("color: rgb(113, 126, 149);")
        self.text_lys_forward.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_lys_forward.setObjectName("text_lys_forward")
        self.slider_lys_forward = QtWidgets.QSlider(Form)
        self.slider_lys_forward.setGeometry(QtCore.QRect(330, 420, 124, 68))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_lys_forward.sizePolicy().hasHeightForWidth())
        self.slider_lys_forward.setSizePolicy(sizePolicy)
        self.slider_lys_forward.setMinimumSize(QtCore.QSize(0, 68))
        self.slider_lys_forward.setMaximumSize(QtCore.QSize(16777215, 68))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.slider_lys_forward.setFont(font)
        self.slider_lys_forward.setStyleSheet("")
        self.slider_lys_forward.setMaximum(100)
        self.slider_lys_forward.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_lys_forward.setInvertedAppearance(False)
        self.slider_lys_forward.setInvertedControls(False)
        self.slider_lys_forward.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBothSides)
        self.slider_lys_forward.setTickInterval(10)
        self.slider_lys_forward.setObjectName("slider_lys_forward")
        self.label_percentage_lys_forward = QtWidgets.QLabel(Form)
        self.label_percentage_lys_forward.setGeometry(QtCore.QRect(470, 440, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_percentage_lys_forward.setFont(font)
        self.label_percentage_lys_forward.setAutoFillBackground(False)
        self.label_percentage_lys_forward.setStyleSheet("background: transparent;")
        self.label_percentage_lys_forward.setScaledContents(False)
        self.label_percentage_lys_forward.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_percentage_lys_forward.setWordWrap(False)
        self.label_percentage_lys_forward.setObjectName("label_percentage_lys_forward")
        self.text_lys_down = QtWidgets.QLabel(Form)
        self.text_lys_down.setGeometry(QtCore.QRect(230, 480, 123, 68))
        self.text_lys_down.setMinimumSize(QtCore.QSize(0, 0))
        self.text_lys_down.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_lys_down.setFont(font)
        self.text_lys_down.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    color: #aaa;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    \n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(110, 105, 118, 255),stop:1 rgba(57, 49, 68, 255));\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background-color: #444;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    border: 1px solid #000;\n"
"    background-color: #444;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #444;\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    padding-right: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #55aaff;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolBar\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"    border: 1px solid #222;\n"
"    background-color: #333;\n"
"    color: #aaa;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(75, 165, 255, 255),stop:0.509615 rgba(119, 187, 255, 255),stop:1 rgba(72, 164, 255, 255));\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    margin-right: 2px;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(65, 155, 245, 255),stop:0.509615 rgba(109, 177, 245, 255),stop:1 rgba(72, 164, 255, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #9999ff;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit{\n"
"    background-color: #fff;\n"
"    color: #000;\n"
"    selection-color: #fff;\n"
"    selection-background-color: #507098;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"QTreeView\n"
"{\n"
"    background-color: #242526;\n"
"       show-decoration-selected: 0;\n"
"       selection-background-color: transparent; /* Used on Mac */\n"
"    alternate-background-color: #404040;\n"
"    selection-color: #fff; /* Used on Mac */\n"
"    font: 8pt;\n"
"    color: #fff;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"QTreeView::item\n"
"{\n"
"    border-top-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:hover\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    show-decoration-selected: 1;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    background-color: #41cd52;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:!active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-closed.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-open.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal \n"
"{\n"
"    background-color: #333;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal \n"
"{\n"
"    width: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    background-color: #333;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical \n"
"{\n"
"    height: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"")
        self.text_lys_down.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_lys_down.setObjectName("text_lys_down")
        self.slider_lys_down = QtWidgets.QSlider(Form)
        self.slider_lys_down.setGeometry(QtCore.QRect(330, 490, 124, 68))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_lys_down.sizePolicy().hasHeightForWidth())
        self.slider_lys_down.setSizePolicy(sizePolicy)
        self.slider_lys_down.setMinimumSize(QtCore.QSize(0, 68))
        self.slider_lys_down.setMaximumSize(QtCore.QSize(16777215, 68))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.slider_lys_down.setFont(font)
        self.slider_lys_down.setStyleSheet("")
        self.slider_lys_down.setMaximum(100)
        self.slider_lys_down.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_lys_down.setInvertedAppearance(False)
        self.slider_lys_down.setInvertedControls(False)
        self.slider_lys_down.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBothSides)
        self.slider_lys_down.setTickInterval(10)
        self.slider_lys_down.setObjectName("slider_lys_down")
        self.label_percentage_lys_down = QtWidgets.QLabel(Form)
        self.label_percentage_lys_down.setGeometry(QtCore.QRect(470, 500, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_percentage_lys_down.setFont(font)
        self.label_percentage_lys_down.setAutoFillBackground(False)
        self.label_percentage_lys_down.setStyleSheet("background: transparent;")
        self.label_percentage_lys_down.setScaledContents(False)
        self.label_percentage_lys_down.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_percentage_lys_down.setWordWrap(False)
        self.label_percentage_lys_down.setObjectName("label_percentage_lys_down")
        self.label_gjsnitt_temp_ROV = QtWidgets.QLabel(Form)
        self.label_gjsnitt_temp_ROV.setGeometry(QtCore.QRect(150, 520, 58, 38))
        self.label_gjsnitt_temp_ROV.setMinimumSize(QtCore.QSize(0, 0))
        self.label_gjsnitt_temp_ROV.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_gjsnitt_temp_ROV.setFont(font)
        self.label_gjsnitt_temp_ROV.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_gjsnitt_temp_ROV.setLineWidth(0)
        self.label_gjsnitt_temp_ROV.setMidLineWidth(0)
        self.label_gjsnitt_temp_ROV.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_gjsnitt_temp_ROV.setObjectName("label_gjsnitt_temp_ROV")
        self.text_gjsnitttemp = QtWidgets.QLabel(Form)
        self.text_gjsnitttemp.setGeometry(QtCore.QRect(20, 520, 58, 38))
        self.text_gjsnitttemp.setMinimumSize(QtCore.QSize(0, 0))
        self.text_gjsnitttemp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_gjsnitttemp.setFont(font)
        self.text_gjsnitttemp.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.text_gjsnitttemp.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.text_gjsnitttemp.setObjectName("text_gjsnitttemp")
        self.thrust_label_1 = QtWidgets.QLabel(Form)
        self.thrust_label_1.setGeometry(QtCore.QRect(220, 260, 61, 51))
        self.thrust_label_1.setObjectName("thrust_label_1")
        self.thrust_label_5 = QtWidgets.QLabel(Form)
        self.thrust_label_5.setGeometry(QtCore.QRect(220, 310, 61, 51))
        self.thrust_label_5.setObjectName("thrust_label_5")
        self.thrust_label_8 = QtWidgets.QLabel(Form)
        self.thrust_label_8.setGeometry(QtCore.QRect(450, 310, 61, 51))
        self.thrust_label_8.setObjectName("thrust_label_8")
        self.thrust_label_2 = QtWidgets.QLabel(Form)
        self.thrust_label_2.setGeometry(QtCore.QRect(300, 260, 61, 51))
        self.thrust_label_2.setObjectName("thrust_label_2")
        self.thrust_label_6 = QtWidgets.QLabel(Form)
        self.thrust_label_6.setGeometry(QtCore.QRect(300, 310, 61, 51))
        self.thrust_label_6.setObjectName("thrust_label_6")
        self.thrust_label_7 = QtWidgets.QLabel(Form)
        self.thrust_label_7.setGeometry(QtCore.QRect(370, 310, 61, 51))
        self.thrust_label_7.setObjectName("thrust_label_7")
        self.thrust_label_3 = QtWidgets.QLabel(Form)
        self.thrust_label_3.setGeometry(QtCore.QRect(370, 260, 61, 51))
        self.thrust_label_3.setObjectName("thrust_label_3")
        self.thrust_label_4 = QtWidgets.QLabel(Form)
        self.thrust_label_4.setGeometry(QtCore.QRect(450, 260, 61, 51))
        self.thrust_label_4.setObjectName("thrust_label_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(750, 400, 111, 161))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(750, 210, 111, 71))
        self.pushButton_6.setObjectName("pushButton_6")
        self.title_effektforbruk_3 = QtWidgets.QLabel(Form)
        self.title_effektforbruk_3.setGeometry(QtCore.QRect(550, 320, 51, 18))
        self.title_effektforbruk_3.setMinimumSize(QtCore.QSize(0, 0))
        self.title_effektforbruk_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_effektforbruk_3.setFont(font)
        self.title_effektforbruk_3.setStyleSheet("")
        self.title_effektforbruk_3.setObjectName("title_effektforbruk_3")
        self.title_effektforbruk_5 = QtWidgets.QLabel(Form)
        self.title_effektforbruk_5.setGeometry(QtCore.QRect(550, 230, 51, 18))
        self.title_effektforbruk_5.setMinimumSize(QtCore.QSize(0, 0))
        self.title_effektforbruk_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_effektforbruk_5.setFont(font)
        self.title_effektforbruk_5.setStyleSheet("")
        self.title_effektforbruk_5.setObjectName("title_effektforbruk_5")
        self.start_transect_2 = QtWidgets.QPushButton(Form)
        self.start_transect_2.setGeometry(QtCore.QRect(560, 160, 301, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_transect_2.sizePolicy().hasHeightForWidth())
        self.start_transect_2.setSizePolicy(sizePolicy)
        self.start_transect_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start_transect_2.setFont(font)
        self.start_transect_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.start_transect_2.setObjectName("start_transect_2")
        self.start_transect_3 = QtWidgets.QPushButton(Form)
        self.start_transect_3.setGeometry(QtCore.QRect(560, 110, 301, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_transect_3.sizePolicy().hasHeightForWidth())
        self.start_transect_3.setSizePolicy(sizePolicy)
        self.start_transect_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start_transect_3.setFont(font)
        self.start_transect_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.start_transect_3.setObjectName("start_transect_3")
        self.start_transect_4 = QtWidgets.QPushButton(Form)
        self.start_transect_4.setGeometry(QtCore.QRect(560, 60, 301, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_transect_4.sizePolicy().hasHeightForWidth())
        self.start_transect_4.setSizePolicy(sizePolicy)
        self.start_transect_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start_transect_4.setFont(font)
        self.start_transect_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.start_transect_4.setObjectName("start_transect_4")
        self.title_kjoremodus_2 = QtWidgets.QLabel(Form)
        self.title_kjoremodus_2.setGeometry(QtCore.QRect(560, 10, 371, 46))
        self.title_kjoremodus_2.setMinimumSize(QtCore.QSize(0, 0))
        self.title_kjoremodus_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_kjoremodus_2.setFont(font)
        self.title_kjoremodus_2.setStyleSheet("")
        self.title_kjoremodus_2.setObjectName("title_kjoremodus_2")
        self.title_motor_2 = QtWidgets.QLabel(Form)
        self.title_motor_2.setGeometry(QtCore.QRect(550, 400, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_motor_2.setFont(font)
        self.title_motor_2.setObjectName("title_motor_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(550, 440, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(550, 490, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(550, 530, 81, 21))
        self.label_4.setObjectName("label_4")
        self.title_motor_3 = QtWidgets.QLabel(Form)
        self.title_motor_3.setGeometry(QtCore.QRect(550, 580, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_motor_3.setFont(font)
        self.title_motor_3.setObjectName("title_motor_3")
        self.label_effekt_elektronikk_2 = QtWidgets.QLabel(Form)
        self.label_effekt_elektronikk_2.setGeometry(QtCore.QRect(650, 220, 74, 42))
        self.label_effekt_elektronikk_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_effekt_elektronikk_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_effekt_elektronikk_2.setFont(font)
        self.label_effekt_elektronikk_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_effekt_elektronikk_2.setLineWidth(0)
        self.label_effekt_elektronikk_2.setMidLineWidth(0)
        self.label_effekt_elektronikk_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_effekt_elektronikk_2.setObjectName("label_effekt_elektronikk_2")
        self.label_effekt_elektronikk_3 = QtWidgets.QLabel(Form)
        self.label_effekt_elektronikk_3.setGeometry(QtCore.QRect(650, 320, 74, 42))
        self.label_effekt_elektronikk_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_effekt_elektronikk_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_effekt_elektronikk_3.setFont(font)
        self.label_effekt_elektronikk_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_effekt_elektronikk_3.setLineWidth(0)
        self.label_effekt_elektronikk_3.setMidLineWidth(0)
        self.label_effekt_elektronikk_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_effekt_elektronikk_3.setObjectName("label_effekt_elektronikk_3")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(750, 310, 111, 61))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_effekt_elektronikk_4 = QtWidgets.QLabel(Form)
        self.label_effekt_elektronikk_4.setGeometry(QtCore.QRect(650, 430, 74, 42))
        self.label_effekt_elektronikk_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_effekt_elektronikk_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_effekt_elektronikk_4.setFont(font)
        self.label_effekt_elektronikk_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_effekt_elektronikk_4.setLineWidth(0)
        self.label_effekt_elektronikk_4.setMidLineWidth(0)
        self.label_effekt_elektronikk_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_effekt_elektronikk_4.setObjectName("label_effekt_elektronikk_4")
        self.label_effekt_elektronikk_5 = QtWidgets.QLabel(Form)
        self.label_effekt_elektronikk_5.setGeometry(QtCore.QRect(650, 470, 74, 42))
        self.label_effekt_elektronikk_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_effekt_elektronikk_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_effekt_elektronikk_5.setFont(font)
        self.label_effekt_elektronikk_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_effekt_elektronikk_5.setLineWidth(0)
        self.label_effekt_elektronikk_5.setMidLineWidth(0)
        self.label_effekt_elektronikk_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_effekt_elektronikk_5.setObjectName("label_effekt_elektronikk_5")
        self.label_effekt_elektronikk_6 = QtWidgets.QLabel(Form)
        self.label_effekt_elektronikk_6.setGeometry(QtCore.QRect(650, 510, 74, 42))
        self.label_effekt_elektronikk_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_effekt_elektronikk_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_effekt_elektronikk_6.setFont(font)
        self.label_effekt_elektronikk_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_effekt_elektronikk_6.setLineWidth(0)
        self.label_effekt_elektronikk_6.setMidLineWidth(0)
        self.label_effekt_elektronikk_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_effekt_elektronikk_6.setObjectName("label_effekt_elektronikk_6")
        self.label_effekt_elektronikk_7 = QtWidgets.QLabel(Form)
        self.label_effekt_elektronikk_7.setGeometry(QtCore.QRect(650, 570, 74, 42))
        self.label_effekt_elektronikk_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_effekt_elektronikk_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_effekt_elektronikk_7.setFont(font)
        self.label_effekt_elektronikk_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_effekt_elektronikk_7.setLineWidth(0)
        self.label_effekt_elektronikk_7.setMidLineWidth(0)
        self.label_effekt_elektronikk_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_effekt_elektronikk_7.setObjectName("label_effekt_elektronikk_7")
        self.openGLWidget = QtWidgets.QOpenGLWidget(Form)
        self.openGLWidget.setGeometry(QtCore.QRect(20, 600, 300, 200))
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 630, 51, 61))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(340, 600, 71, 16))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 690, 51, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 630, 75, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 692, 75, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(420, 600, 47, 13))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn1.setText(_translate("Form", "Manuell kjøring"))
        self.btn_autonom_docking.setText(_translate("Form", "Autonom docking"))
        self.start_transect.setText(_translate("Form", "Start transect"))
        self.title_effektforbruk.setText(_translate("Form", "EFFEKTFORBRUK"))
        self.text_effekt_elektronikk.setText(_translate("Form", "Elektronikk:"))
        self.text_effekt_elektronikk.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.text_effekt_thrustere.setText(_translate("Form", "Thrustere:"))
        self.text_effekt_thrustere.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.text_effekt_manipulator.setText(_translate("Form", "Manipulator:"))
        self.text_effekt_manipulator.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.label_effekt_elektronikk.setText(_translate("Form", "---"))
        self.label_effekt_elektronikk.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_effekt_elektronikk.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label_effekt_thrustere.setText(_translate("Form", "---"))
        self.label_effekt_thrustere.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_effekt_thrustere.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label_effekt_manipulator.setText(_translate("Form", "---"))
        self.label_effekt_manipulator.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_effekt_manipulator.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.title_temp_ROV.setText(_translate("Form", "TEMPERATUR I ROV"))
        self.text_hovedkort.setText(_translate("Form", "Hovedkort:"))
        self.text_hovedkort.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.label_temp_ROV_hovedkort.setText(_translate("Form", "---"))
        self.label_temp_ROV_hovedkort.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_temp_ROV_hovedkort.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.text_kraftkort.setText(_translate("Form", "Kraftkort:"))
        self.text_kraftkort.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.text_sensorkort.setText(_translate("Form", "Sensorkort:"))
        self.text_sensorkort.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.label_temp_ROV_kraftkort.setText(_translate("Form", "---"))
        self.label_temp_ROV_kraftkort.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_temp_ROV_kraftkort.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label_temp_ROV_sensorkort.setText(_translate("Form", "---"))
        self.label_temp_ROV_sensorkort.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_temp_ROV_sensorkort.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.title_motor.setText(_translate("Form", "MOTORPÅDRAG"))
        self.text_rov.setText(_translate("Form", "ROV"))
        self.text_rov.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.title_kjoremodus.setText(_translate("Form", "KJØREMODUS"))
        self.lys_title.setText(_translate("Form", "LYS"))
        self.text_lys_forward.setText(_translate("Form", "Top Light"))
        self.text_lys_forward.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.label_percentage_lys_forward.setText(_translate("Form", "<html><head/><body><span>0</span><span style=\"vertical-align:super;\">%</span></body></html>"))
        self.text_lys_down.setText(_translate("Form", "Bottom Light"))
        self.text_lys_down.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.label_percentage_lys_down.setText(_translate("Form", "<html><head/><body><span>0</span><span style=\"vertical-align:super;\">%</span></body></html>"))
        self.label_gjsnitt_temp_ROV.setText(_translate("Form", "---"))
        self.label_gjsnitt_temp_ROV.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_gjsnitt_temp_ROV.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.text_gjsnitttemp.setText(_translate("Form", "Gj.snitt:"))
        self.text_gjsnitttemp.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.thrust_label_1.setText(_translate("Form", "----------"))
        self.thrust_label_5.setText(_translate("Form", "----------"))
        self.thrust_label_8.setText(_translate("Form", "----------"))
        self.thrust_label_2.setText(_translate("Form", "----------"))
        self.thrust_label_6.setText(_translate("Form", "----------"))
        self.thrust_label_7.setText(_translate("Form", "----------"))
        self.thrust_label_3.setText(_translate("Form", "----------"))
        self.thrust_label_4.setText(_translate("Form", "----------"))
        self.pushButton_5.setText(_translate("Form", "Nullpunkt Vinkler"))
        self.pushButton_6.setText(_translate("Form", "Kalibrer IMU"))
        self.title_effektforbruk_3.setText(_translate("Form", "Dybde"))
        self.title_effektforbruk_5.setText(_translate("Form", "Gyro:"))
        self.start_transect_2.setText(_translate("Form", "Reset Manipulator "))
        self.start_transect_3.setText(_translate("Form", "Reset Thruster"))
        self.start_transect_4.setText(_translate("Form", "Reset 5V "))
        self.title_kjoremodus_2.setText(_translate("Form", "Sikringer"))
        self.title_motor_2.setText(_translate("Form", "Vinkler:"))
        self.label_2.setText(_translate("Form", "Vinkel 1:"))
        self.label_3.setText(_translate("Form", "Vinkel 2:"))
        self.label_4.setText(_translate("Form", "Vinkel 3:"))
        self.title_motor_3.setText(_translate("Form", "Akelerasjon:"))
        self.label_effekt_elektronikk_2.setText(_translate("Form", "---"))
        self.label_effekt_elektronikk_2.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_effekt_elektronikk_2.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label_effekt_elektronikk_3.setText(_translate("Form", "---"))
        self.label_effekt_elektronikk_3.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_effekt_elektronikk_3.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.pushButton_8.setText(_translate("Form", "Nullpunkt Dybde"))
        self.label_effekt_elektronikk_4.setText(_translate("Form", "---"))
        self.label_effekt_elektronikk_4.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_effekt_elektronikk_4.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label_effekt_elektronikk_5.setText(_translate("Form", "---"))
        self.label_effekt_elektronikk_5.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_effekt_elektronikk_5.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label_effekt_elektronikk_6.setText(_translate("Form", "---"))
        self.label_effekt_elektronikk_6.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_effekt_elektronikk_6.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label_effekt_elektronikk_7.setText(_translate("Form", "---"))
        self.label_effekt_elektronikk_7.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.label_effekt_elektronikk_7.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.pushButton.setText(_translate("Form", "/\\"))
        self.label.setText(_translate("Form", "Camera Tilt :"))
        self.pushButton_2.setText(_translate("Form", "V"))
        self.pushButton_3.setText(_translate("Form", "Take"))
        self.pushButton_4.setText(_translate("Form", "Save"))
        self.label_5.setText(_translate("Form", "Picture :"))
