# Form implementation generated from reading ui file 'd:\Bachelor_GUI\gui\window1.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(902, 819)
        Form.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    color: #aaa;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    \n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(110, 105, 118, 255),stop:1 rgba(57, 49, 68, 255));\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background-color: #444;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    border: 1px solid #000;\n"
"    background-color: #444;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #444;\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    padding-right: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #55aaff;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolBar\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"    border: 1px solid #222;\n"
"    background-color: #333;\n"
"    color: #aaa;\n"
"\n"
"}\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(75, 165, 255, 255),stop:0.509615 rgba(119, 187, 255, 255),stop:1 rgba(72, 164, 255, 255));\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    margin-right: 2px;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(135, 206, 250, 255),stop:0.509615 rgba(176, 224, 230, 255),stop:1 rgba(135, 206, 250, 255));\n"
"}\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(65, 155, 245, 255),stop:0.509615 rgba(109, 177, 245, 255),stop:1 rgba(72, 164, 255, 255));\n"
"\n"
"}\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #9999ff;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit{\n"
"    background-color: #fff;\n"
"    color: #000;\n"
"    selection-color: #fff;\n"
"    selection-background-color: #507098;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"QTreeView\n"
"{\n"
"    background-color: #242526;\n"
"       show-decoration-selected: 0;\n"
"       selection-background-color: transparent; /* Used on Mac */\n"
"    alternate-background-color: #404040;\n"
"    selection-color: #fff; /* Used on Mac */\n"
"    font: 8pt;\n"
"    color: #fff;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"QTreeView::item\n"
"{\n"
"    border-top-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:hover\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    show-decoration-selected: 1;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    background-color: #41cd52;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:!active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-closed.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-open.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal \n"
"{\n"
"    background-color: #333;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal \n"
"{\n"
"    width: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    background-color: #333;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical \n"
"{\n"
"    height: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"")
        self.btnManuell = QtWidgets.QPushButton(Form)
        self.btnManuell.setEnabled(True)
        self.btnManuell.setGeometry(QtCore.QRect(10, 50, 541, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnManuell.sizePolicy().hasHeightForWidth())
        self.btnManuell.setSizePolicy(sizePolicy)
        self.btnManuell.setMinimumSize(QtCore.QSize(0, 0))
        self.btnManuell.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnManuell.setFont(font)
        self.btnManuell.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnManuell.setCheckable(False)
        self.btnManuell.setChecked(False)
        self.btnManuell.setAutoRepeat(False)
        self.btnManuell.setObjectName("btnManuell")
        self.btnAutonom = QtWidgets.QPushButton(Form)
        self.btnAutonom.setGeometry(QtCore.QRect(10, 100, 541, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAutonom.sizePolicy().hasHeightForWidth())
        self.btnAutonom.setSizePolicy(sizePolicy)
        self.btnAutonom.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnAutonom.setFont(font)
        self.btnAutonom.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAutonom.setObjectName("btnAutonom")
        self.btnFrogCount = QtWidgets.QPushButton(Form)
        self.btnFrogCount.setGeometry(QtCore.QRect(10, 150, 541, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFrogCount.sizePolicy().hasHeightForWidth())
        self.btnFrogCount.setSizePolicy(sizePolicy)
        self.btnFrogCount.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnFrogCount.setFont(font)
        self.btnFrogCount.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFrogCount.setObjectName("btnFrogCount")
        self.titleEffekt = QtWidgets.QLabel(Form)
        self.titleEffekt.setGeometry(QtCore.QRect(20, 350, 191, 18))
        self.titleEffekt.setMinimumSize(QtCore.QSize(0, 0))
        self.titleEffekt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleEffekt.setFont(font)
        self.titleEffekt.setStyleSheet("")
        self.titleEffekt.setObjectName("titleEffekt")
        self.text_effekt_elektronikk = QtWidgets.QLabel(Form)
        self.text_effekt_elektronikk.setGeometry(QtCore.QRect(20, 370, 113, 42))
        self.text_effekt_elektronikk.setMinimumSize(QtCore.QSize(0, 0))
        self.text_effekt_elektronikk.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_effekt_elektronikk.setFont(font)
        self.text_effekt_elektronikk.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_effekt_elektronikk.setObjectName("text_effekt_elektronikk")
        self.text_effekt_thrustere = QtWidgets.QLabel(Form)
        self.text_effekt_thrustere.setGeometry(QtCore.QRect(20, 410, 113, 42))
        self.text_effekt_thrustere.setMinimumSize(QtCore.QSize(0, 0))
        self.text_effekt_thrustere.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_effekt_thrustere.setFont(font)
        self.text_effekt_thrustere.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.text_effekt_thrustere.setObjectName("text_effekt_thrustere")
        self.text_effekt_manipulator = QtWidgets.QLabel(Form)
        self.text_effekt_manipulator.setGeometry(QtCore.QRect(20, 450, 113, 42))
        self.text_effekt_manipulator.setMinimumSize(QtCore.QSize(0, 0))
        self.text_effekt_manipulator.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_effekt_manipulator.setFont(font)
        self.text_effekt_manipulator.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_effekt_manipulator.setObjectName("text_effekt_manipulator")
        self.labelEffektElektronikk = QtWidgets.QLabel(Form)
        self.labelEffektElektronikk.setGeometry(QtCore.QRect(140, 370, 74, 42))
        self.labelEffektElektronikk.setMinimumSize(QtCore.QSize(0, 0))
        self.labelEffektElektronikk.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelEffektElektronikk.setFont(font)
        self.labelEffektElektronikk.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelEffektElektronikk.setLineWidth(0)
        self.labelEffektElektronikk.setMidLineWidth(0)
        self.labelEffektElektronikk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelEffektElektronikk.setObjectName("labelEffektElektronikk")
        self.labelEffektThrustere = QtWidgets.QLabel(Form)
        self.labelEffektThrustere.setGeometry(QtCore.QRect(140, 410, 74, 42))
        self.labelEffektThrustere.setMinimumSize(QtCore.QSize(0, 0))
        self.labelEffektThrustere.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelEffektThrustere.setFont(font)
        self.labelEffektThrustere.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelEffektThrustere.setLineWidth(0)
        self.labelEffektThrustere.setMidLineWidth(0)
        self.labelEffektThrustere.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelEffektThrustere.setObjectName("labelEffektThrustere")
        self.labelEffektManipulator = QtWidgets.QLabel(Form)
        self.labelEffektManipulator.setGeometry(QtCore.QRect(140, 450, 74, 42))
        self.labelEffektManipulator.setMinimumSize(QtCore.QSize(0, 0))
        self.labelEffektManipulator.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelEffektManipulator.setFont(font)
        self.labelEffektManipulator.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelEffektManipulator.setLineWidth(0)
        self.labelEffektManipulator.setMidLineWidth(0)
        self.labelEffektManipulator.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelEffektManipulator.setObjectName("labelEffektManipulator")
        self.title_temp_ROV = QtWidgets.QLabel(Form)
        self.title_temp_ROV.setGeometry(QtCore.QRect(20, 540, 171, 18))
        self.title_temp_ROV.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_temp_ROV.setFont(font)
        self.title_temp_ROV.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.title_temp_ROV.setObjectName("title_temp_ROV")
        self.text_hovedkort = QtWidgets.QLabel(Form)
        self.text_hovedkort.setGeometry(QtCore.QRect(20, 560, 113, 38))
        self.text_hovedkort.setMinimumSize(QtCore.QSize(0, 0))
        self.text_hovedkort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_hovedkort.setFont(font)
        self.text_hovedkort.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.text_hovedkort.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.text_hovedkort.setObjectName("text_hovedkort")
        self.labelTempVann = QtWidgets.QLabel(Form)
        self.labelTempVann.setGeometry(QtCore.QRect(140, 560, 74, 38))
        self.labelTempVann.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTempVann.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTempVann.setFont(font)
        self.labelTempVann.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelTempVann.setLineWidth(0)
        self.labelTempVann.setMidLineWidth(0)
        self.labelTempVann.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTempVann.setObjectName("labelTempVann")
        self.text_kraftkort = QtWidgets.QLabel(Form)
        self.text_kraftkort.setGeometry(QtCore.QRect(20, 600, 113, 38))
        self.text_kraftkort.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_kraftkort.setFont(font)
        self.text_kraftkort.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_kraftkort.setObjectName("text_kraftkort")
        self.text_sensorkort = QtWidgets.QLabel(Form)
        self.text_sensorkort.setGeometry(QtCore.QRect(20, 640, 113, 38))
        self.text_sensorkort.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_sensorkort.setFont(font)
        self.text_sensorkort.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_sensorkort.setObjectName("text_sensorkort")
        self.labelTempVannMSB = QtWidgets.QLabel(Form)
        self.labelTempVannMSB.setGeometry(QtCore.QRect(140, 600, 74, 38))
        self.labelTempVannMSB.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTempVannMSB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTempVannMSB.setFont(font)
        self.labelTempVannMSB.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelTempVannMSB.setLineWidth(0)
        self.labelTempVannMSB.setMidLineWidth(0)
        self.labelTempVannMSB.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTempVannMSB.setObjectName("labelTempVannMSB")
        self.labelTempSensorkort = QtWidgets.QLabel(Form)
        self.labelTempSensorkort.setGeometry(QtCore.QRect(140, 640, 74, 38))
        self.labelTempSensorkort.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTempSensorkort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTempSensorkort.setFont(font)
        self.labelTempSensorkort.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelTempSensorkort.setLineWidth(0)
        self.labelTempSensorkort.setMidLineWidth(0)
        self.labelTempSensorkort.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTempSensorkort.setObjectName("labelTempSensorkort")
        self.title_motor = QtWidgets.QLabel(Form)
        self.title_motor.setGeometry(QtCore.QRect(210, 210, 421, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_motor.setFont(font)
        self.title_motor.setObjectName("title_motor")
        self.text_rov = QtWidgets.QLabel(Form)
        self.text_rov.setGeometry(QtCore.QRect(210, 230, 357, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_rov.setFont(font)
        self.text_rov.setStyleSheet("color: rgb(113, 126, 149);")
        self.text_rov.setLineWidth(1)
        self.text_rov.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.text_rov.setObjectName("text_rov")
        self.title_kjoremodus = QtWidgets.QLabel(Form)
        self.title_kjoremodus.setGeometry(QtCore.QRect(20, 0, 371, 46))
        self.title_kjoremodus.setMinimumSize(QtCore.QSize(0, 0))
        self.title_kjoremodus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_kjoremodus.setFont(font)
        self.title_kjoremodus.setStyleSheet("")
        self.title_kjoremodus.setObjectName("title_kjoremodus")
        self.titleLys = QtWidgets.QLabel(Form)
        self.titleLys.setGeometry(QtCore.QRect(550, 570, 123, 18))
        self.titleLys.setMinimumSize(QtCore.QSize(0, 0))
        self.titleLys.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleLys.setFont(font)
        self.titleLys.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.titleLys.setObjectName("titleLys")
        self.text_lys_forward = QtWidgets.QLabel(Form)
        self.text_lys_forward.setGeometry(QtCore.QRect(560, 590, 123, 68))
        self.text_lys_forward.setMinimumSize(QtCore.QSize(0, 0))
        self.text_lys_forward.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_lys_forward.setFont(font)
        self.text_lys_forward.setStyleSheet("color: rgb(113, 126, 149);")
        self.text_lys_forward.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_lys_forward.setObjectName("text_lys_forward")
        self.slider_lys_forward = QtWidgets.QSlider(Form)
        self.slider_lys_forward.setGeometry(QtCore.QRect(660, 590, 124, 68))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_lys_forward.sizePolicy().hasHeightForWidth())
        self.slider_lys_forward.setSizePolicy(sizePolicy)
        self.slider_lys_forward.setMinimumSize(QtCore.QSize(0, 68))
        self.slider_lys_forward.setMaximumSize(QtCore.QSize(16777215, 68))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.slider_lys_forward.setFont(font)
        self.slider_lys_forward.setStyleSheet("")
        self.slider_lys_forward.setMaximum(100)
        self.slider_lys_forward.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_lys_forward.setInvertedAppearance(False)
        self.slider_lys_forward.setInvertedControls(False)
        self.slider_lys_forward.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBothSides)
        self.slider_lys_forward.setTickInterval(10)
        self.slider_lys_forward.setObjectName("slider_lys_forward")
        self.label_percentage_lys_forward = QtWidgets.QLabel(Form)
        self.label_percentage_lys_forward.setGeometry(QtCore.QRect(800, 610, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_percentage_lys_forward.setFont(font)
        self.label_percentage_lys_forward.setAutoFillBackground(False)
        self.label_percentage_lys_forward.setStyleSheet("background: transparent;")
        self.label_percentage_lys_forward.setScaledContents(False)
        self.label_percentage_lys_forward.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_percentage_lys_forward.setWordWrap(False)
        self.label_percentage_lys_forward.setObjectName("label_percentage_lys_forward")
        self.text_lys_down = QtWidgets.QLabel(Form)
        self.text_lys_down.setGeometry(QtCore.QRect(560, 650, 123, 68))
        self.text_lys_down.setMinimumSize(QtCore.QSize(0, 0))
        self.text_lys_down.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_lys_down.setFont(font)
        self.text_lys_down.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    color: #aaa;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    \n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(110, 105, 118, 255),stop:1 rgba(57, 49, 68, 255));\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background-color: #444;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    border: 1px solid #000;\n"
"    background-color: #444;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #444;\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    padding-right: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #55aaff;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolBar\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"    border: 1px solid #222;\n"
"    background-color: #333;\n"
"    color: #aaa;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(75, 165, 255, 255),stop:0.509615 rgba(119, 187, 255, 255),stop:1 rgba(72, 164, 255, 255));\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    margin-right: 2px;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(65, 155, 245, 255),stop:0.509615 rgba(109, 177, 245, 255),stop:1 rgba(72, 164, 255, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #9999ff;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit{\n"
"    background-color: #fff;\n"
"    color: #000;\n"
"    selection-color: #fff;\n"
"    selection-background-color: #507098;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"QTreeView\n"
"{\n"
"    background-color: #242526;\n"
"       show-decoration-selected: 0;\n"
"       selection-background-color: transparent; /* Used on Mac */\n"
"    alternate-background-color: #404040;\n"
"    selection-color: #fff; /* Used on Mac */\n"
"    font: 8pt;\n"
"    color: #fff;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"QTreeView::item\n"
"{\n"
"    border-top-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:hover\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    show-decoration-selected: 1;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    background-color: #41cd52;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:!active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-closed.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-open.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal \n"
"{\n"
"    background-color: #333;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal \n"
"{\n"
"    width: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    background-color: #333;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical \n"
"{\n"
"    height: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"")
        self.text_lys_down.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_lys_down.setObjectName("text_lys_down")
        self.slider_lys_down = QtWidgets.QSlider(Form)
        self.slider_lys_down.setGeometry(QtCore.QRect(660, 660, 124, 68))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_lys_down.sizePolicy().hasHeightForWidth())
        self.slider_lys_down.setSizePolicy(sizePolicy)
        self.slider_lys_down.setMinimumSize(QtCore.QSize(0, 68))
        self.slider_lys_down.setMaximumSize(QtCore.QSize(16777215, 68))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.slider_lys_down.setFont(font)
        self.slider_lys_down.setStyleSheet("")
        self.slider_lys_down.setMaximum(100)
        self.slider_lys_down.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_lys_down.setInvertedAppearance(False)
        self.slider_lys_down.setInvertedControls(False)
        self.slider_lys_down.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBothSides)
        self.slider_lys_down.setTickInterval(10)
        self.slider_lys_down.setObjectName("slider_lys_down")
        self.label_percentage_lys_down = QtWidgets.QLabel(Form)
        self.label_percentage_lys_down.setGeometry(QtCore.QRect(800, 670, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_percentage_lys_down.setFont(font)
        self.label_percentage_lys_down.setAutoFillBackground(False)
        self.label_percentage_lys_down.setStyleSheet("background: transparent;")
        self.label_percentage_lys_down.setScaledContents(False)
        self.label_percentage_lys_down.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_percentage_lys_down.setWordWrap(False)
        self.label_percentage_lys_down.setObjectName("label_percentage_lys_down")
        self.labelSnittTemp = QtWidgets.QLabel(Form)
        self.labelSnittTemp.setGeometry(QtCore.QRect(150, 720, 58, 38))
        self.labelSnittTemp.setMinimumSize(QtCore.QSize(0, 0))
        self.labelSnittTemp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelSnittTemp.setFont(font)
        self.labelSnittTemp.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelSnittTemp.setLineWidth(0)
        self.labelSnittTemp.setMidLineWidth(0)
        self.labelSnittTemp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSnittTemp.setObjectName("labelSnittTemp")
        self.text_gjsnitttemp = QtWidgets.QLabel(Form)
        self.text_gjsnitttemp.setGeometry(QtCore.QRect(20, 720, 58, 38))
        self.text_gjsnitttemp.setMinimumSize(QtCore.QSize(0, 0))
        self.text_gjsnitttemp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_gjsnitttemp.setFont(font)
        self.text_gjsnitttemp.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.text_gjsnitttemp.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.text_gjsnitttemp.setObjectName("text_gjsnitttemp")
        self.thrust_label_1 = QtWidgets.QLabel(Form)
        self.thrust_label_1.setGeometry(QtCore.QRect(280, 280, 61, 51))
        self.thrust_label_1.setObjectName("thrust_label_1")
        self.thrust_label_5 = QtWidgets.QLabel(Form)
        self.thrust_label_5.setGeometry(QtCore.QRect(280, 330, 61, 51))
        self.thrust_label_5.setObjectName("thrust_label_5")
        self.thrust_label_8 = QtWidgets.QLabel(Form)
        self.thrust_label_8.setGeometry(QtCore.QRect(360, 480, 61, 51))
        self.thrust_label_8.setObjectName("thrust_label_8")
        self.thrust_label_2 = QtWidgets.QLabel(Form)
        self.thrust_label_2.setGeometry(QtCore.QRect(360, 280, 61, 51))
        self.thrust_label_2.setObjectName("thrust_label_2")
        self.thrust_label_6 = QtWidgets.QLabel(Form)
        self.thrust_label_6.setGeometry(QtCore.QRect(360, 330, 61, 51))
        self.thrust_label_6.setObjectName("thrust_label_6")
        self.thrust_label_7 = QtWidgets.QLabel(Form)
        self.thrust_label_7.setGeometry(QtCore.QRect(280, 480, 61, 51))
        self.thrust_label_7.setObjectName("thrust_label_7")
        self.thrust_label_3 = QtWidgets.QLabel(Form)
        self.thrust_label_3.setGeometry(QtCore.QRect(280, 430, 61, 51))
        self.thrust_label_3.setObjectName("thrust_label_3")
        self.thrust_label_4 = QtWidgets.QLabel(Form)
        self.thrust_label_4.setGeometry(QtCore.QRect(360, 430, 61, 51))
        self.thrust_label_4.setObjectName("thrust_label_4")
        self.btnNullpunktVinkler = QtWidgets.QPushButton(Form)
        self.btnNullpunktVinkler.setGeometry(QtCore.QRect(740, 390, 111, 161))
        self.btnNullpunktVinkler.setObjectName("btnNullpunktVinkler")
        self.btnKalibrerIMU = QtWidgets.QPushButton(Form)
        self.btnKalibrerIMU.setGeometry(QtCore.QRect(750, 200, 111, 71))
        self.btnKalibrerIMU.setObjectName("btnKalibrerIMU")
        self.titleDybde = QtWidgets.QLabel(Form)
        self.titleDybde.setGeometry(QtCore.QRect(550, 310, 51, 18))
        self.titleDybde.setMinimumSize(QtCore.QSize(0, 0))
        self.titleDybde.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleDybde.setFont(font)
        self.titleDybde.setStyleSheet("")
        self.titleDybde.setObjectName("titleDybde")
        self.btnResetManipulator = QtWidgets.QPushButton(Form)
        self.btnResetManipulator.setGeometry(QtCore.QRect(560, 150, 301, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResetManipulator.sizePolicy().hasHeightForWidth())
        self.btnResetManipulator.setSizePolicy(sizePolicy)
        self.btnResetManipulator.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnResetManipulator.setFont(font)
        self.btnResetManipulator.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnResetManipulator.setObjectName("btnResetManipulator")
        self.btnResetThruster = QtWidgets.QPushButton(Form)
        self.btnResetThruster.setGeometry(QtCore.QRect(560, 100, 301, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResetThruster.sizePolicy().hasHeightForWidth())
        self.btnResetThruster.setSizePolicy(sizePolicy)
        self.btnResetThruster.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnResetThruster.setFont(font)
        self.btnResetThruster.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnResetThruster.setObjectName("btnResetThruster")
        self.btnReset5V = QtWidgets.QPushButton(Form)
        self.btnReset5V.setGeometry(QtCore.QRect(560, 50, 301, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReset5V.sizePolicy().hasHeightForWidth())
        self.btnReset5V.setSizePolicy(sizePolicy)
        self.btnReset5V.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnReset5V.setFont(font)
        self.btnReset5V.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnReset5V.setObjectName("btnReset5V")
        self.title_kjoremodus_2 = QtWidgets.QLabel(Form)
        self.title_kjoremodus_2.setGeometry(QtCore.QRect(560, 0, 371, 46))
        self.title_kjoremodus_2.setMinimumSize(QtCore.QSize(0, 0))
        self.title_kjoremodus_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_kjoremodus_2.setFont(font)
        self.title_kjoremodus_2.setStyleSheet("")
        self.title_kjoremodus_2.setObjectName("title_kjoremodus_2")
        self.titleVinkler = QtWidgets.QLabel(Form)
        self.titleVinkler.setGeometry(QtCore.QRect(550, 390, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleVinkler.setFont(font)
        self.titleVinkler.setObjectName("titleVinkler")
        self.vinkel1 = QtWidgets.QLabel(Form)
        self.vinkel1.setGeometry(QtCore.QRect(550, 430, 47, 13))
        self.vinkel1.setObjectName("vinkel1")
        self.Vinkel2 = QtWidgets.QLabel(Form)
        self.Vinkel2.setGeometry(QtCore.QRect(550, 480, 47, 13))
        self.Vinkel2.setObjectName("Vinkel2")
        self.Vinkel3 = QtWidgets.QLabel(Form)
        self.Vinkel3.setGeometry(QtCore.QRect(550, 520, 81, 21))
        self.Vinkel3.setObjectName("Vinkel3")
        self.titleAkselerasjon = QtWidgets.QLabel(Form)
        self.titleAkselerasjon.setGeometry(QtCore.QRect(550, 740, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleAkselerasjon.setFont(font)
        self.titleAkselerasjon.setObjectName("titleAkselerasjon")
        self.labelDybde = QtWidgets.QLabel(Form)
        self.labelDybde.setGeometry(QtCore.QRect(650, 310, 74, 42))
        self.labelDybde.setMinimumSize(QtCore.QSize(0, 0))
        self.labelDybde.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelDybde.setFont(font)
        self.labelDybde.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelDybde.setLineWidth(0)
        self.labelDybde.setMidLineWidth(0)
        self.labelDybde.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelDybde.setObjectName("labelDybde")
        self.btnNullpunktDybde = QtWidgets.QPushButton(Form)
        self.btnNullpunktDybde.setGeometry(QtCore.QRect(750, 300, 111, 61))
        self.btnNullpunktDybde.setObjectName("btnNullpunktDybde")
        self.labelRull = QtWidgets.QLabel(Form)
        self.labelRull.setGeometry(QtCore.QRect(650, 420, 74, 42))
        self.labelRull.setMinimumSize(QtCore.QSize(0, 0))
        self.labelRull.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRull.setFont(font)
        self.labelRull.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelRull.setLineWidth(0)
        self.labelRull.setMidLineWidth(0)
        self.labelRull.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelRull.setObjectName("labelRull")
        self.labelStamp = QtWidgets.QLabel(Form)
        self.labelStamp.setGeometry(QtCore.QRect(650, 460, 74, 42))
        self.labelStamp.setMinimumSize(QtCore.QSize(0, 0))
        self.labelStamp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelStamp.setFont(font)
        self.labelStamp.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelStamp.setLineWidth(0)
        self.labelStamp.setMidLineWidth(0)
        self.labelStamp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelStamp.setObjectName("labelStamp")
        self.labelGir = QtWidgets.QLabel(Form)
        self.labelGir.setGeometry(QtCore.QRect(650, 500, 74, 42))
        self.labelGir.setMinimumSize(QtCore.QSize(0, 0))
        self.labelGir.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelGir.setFont(font)
        self.labelGir.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelGir.setLineWidth(0)
        self.labelGir.setMidLineWidth(0)
        self.labelGir.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelGir.setObjectName("labelGir")
        self.labelAccel = QtWidgets.QLabel(Form)
        self.labelAccel.setGeometry(QtCore.QRect(650, 730, 74, 42))
        self.labelAccel.setMinimumSize(QtCore.QSize(0, 0))
        self.labelAccel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelAccel.setFont(font)
        self.labelAccel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelAccel.setLineWidth(0)
        self.labelAccel.setMidLineWidth(0)
        self.labelAccel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelAccel.setObjectName("labelAccel")
        self.titleNewWindow = QtWidgets.QLabel(Form)
        self.titleNewWindow.setGeometry(QtCore.QRect(20, 195, 371, 61))
        self.titleNewWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.titleNewWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleNewWindow.setFont(font)
        self.titleNewWindow.setStyleSheet("")
        self.titleNewWindow.setObjectName("titleNewWindow")
        self.showNewWindowButton = QtWidgets.QPushButton(Form)
        self.showNewWindowButton.setGeometry(QtCore.QRect(10, 250, 181, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showNewWindowButton.sizePolicy().hasHeightForWidth())
        self.showNewWindowButton.setSizePolicy(sizePolicy)
        self.showNewWindowButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.showNewWindowButton.setFont(font)
        self.showNewWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.showNewWindowButton.setObjectName("showNewWindowButton")
        self.text_sensorkort_2 = QtWidgets.QLabel(Form)
        self.text_sensorkort_2.setGeometry(QtCore.QRect(20, 680, 113, 38))
        self.text_sensorkort_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_sensorkort_2.setFont(font)
        self.text_sensorkort_2.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.text_sensorkort_2.setObjectName("text_sensorkort_2")
        self.labelTempSensorkortMSB = QtWidgets.QLabel(Form)
        self.labelTempSensorkortMSB.setGeometry(QtCore.QRect(140, 680, 74, 38))
        self.labelTempSensorkortMSB.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTempSensorkortMSB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTempSensorkortMSB.setFont(font)
        self.labelTempSensorkortMSB.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelTempSensorkortMSB.setLineWidth(0)
        self.labelTempSensorkortMSB.setMidLineWidth(0)
        self.labelTempSensorkortMSB.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTempSensorkortMSB.setObjectName("labelTempSensorkortMSB")
        self.title_temp_ROV_2 = QtWidgets.QLabel(Form)
        self.title_temp_ROV_2.setGeometry(QtCore.QRect(250, 538, 191, 20))
        self.title_temp_ROV_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_temp_ROV_2.setFont(font)
        self.title_temp_ROV_2.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.title_temp_ROV_2.setObjectName("title_temp_ROV_2")
        self.labelLekkasjeAlarm_2 = QtWidgets.QLabel(Form)
        self.labelLekkasjeAlarm_2.setGeometry(QtCore.QRect(610, 690, 119, 43))
        self.labelLekkasjeAlarm_2.setMinimumSize(QtCore.QSize(0, 0))
        self.labelLekkasjeAlarm_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLekkasjeAlarm_2.setFont(font)
        self.labelLekkasjeAlarm_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelLekkasjeAlarm_2.setLineWidth(0)
        self.labelLekkasjeAlarm_2.setMidLineWidth(0)
        self.labelLekkasjeAlarm_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelLekkasjeAlarm_2.setObjectName("labelLekkasjeAlarm_2")
        self.labelLekkasjeAlarm = QtWidgets.QLabel(Form)
        self.labelLekkasjeAlarm.setGeometry(QtCore.QRect(400, 590, 101, 31))
        self.labelLekkasjeAlarm.setMinimumSize(QtCore.QSize(0, 0))
        self.labelLekkasjeAlarm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLekkasjeAlarm.setFont(font)
        self.labelLekkasjeAlarm.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelLekkasjeAlarm.setLineWidth(0)
        self.labelLekkasjeAlarm.setMidLineWidth(0)
        self.labelLekkasjeAlarm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelLekkasjeAlarm.setObjectName("labelLekkasjeAlarm")
        self.labelIMUAlarm = QtWidgets.QLabel(Form)
        self.labelIMUAlarm.setGeometry(QtCore.QRect(410, 730, 81, 31))
        self.labelIMUAlarm.setMinimumSize(QtCore.QSize(0, 0))
        self.labelIMUAlarm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelIMUAlarm.setFont(font)
        self.labelIMUAlarm.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelIMUAlarm.setLineWidth(0)
        self.labelIMUAlarm.setMidLineWidth(0)
        self.labelIMUAlarm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelIMUAlarm.setObjectName("labelIMUAlarm")
        self.labelTrykkAlarm = QtWidgets.QLabel(Form)
        self.labelTrykkAlarm.setGeometry(QtCore.QRect(410, 630, 81, 31))
        self.labelTrykkAlarm.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTrykkAlarm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTrykkAlarm.setFont(font)
        self.labelTrykkAlarm.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelTrykkAlarm.setLineWidth(0)
        self.labelTrykkAlarm.setMidLineWidth(0)
        self.labelTrykkAlarm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTrykkAlarm.setObjectName("labelTrykkAlarm")
        self.labelTempAlarm = QtWidgets.QLabel(Form)
        self.labelTempAlarm.setGeometry(QtCore.QRect(390, 670, 111, 41))
        self.labelTempAlarm.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTempAlarm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTempAlarm.setFont(font)
        self.labelTempAlarm.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.labelTempAlarm.setLineWidth(0)
        self.labelTempAlarm.setMidLineWidth(0)
        self.labelTempAlarm.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTempAlarm.setObjectName("labelTempAlarm")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(260, 590, 129, 43))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(260, 680, 61, 41))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(260, 630, 61, 51))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(260, 720, 91, 41))
        self.label_4.setObjectName("label_4")
        self.btnTakePic = QtWidgets.QPushButton(Form)
        self.btnTakePic.setGeometry(QtCore.QRect(450, 310, 75, 61))
        self.btnTakePic.setObjectName("btnTakePic")
        self.btnRecord = QtWidgets.QPushButton(Form)
        self.btnRecord.setGeometry(QtCore.QRect(450, 430, 75, 61))
        self.btnRecord.setObjectName("btnRecord")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnManuell.setText(_translate("Form", "Manuell kjøring"))
        self.btnAutonom.setText(_translate("Form", "Autonom docking"))
        self.btnFrogCount.setText(_translate("Form", "Start Frog Count"))
        self.titleEffekt.setText(_translate("Form", "EFFEKTFORBRUK"))
        self.text_effekt_elektronikk.setText(_translate("Form", "Elektronikk:"))
        self.text_effekt_elektronikk.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.text_effekt_thrustere.setText(_translate("Form", "Thrustere:"))
        self.text_effekt_thrustere.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.text_effekt_manipulator.setText(_translate("Form", "Manipulator:"))
        self.text_effekt_manipulator.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.labelEffektElektronikk.setText(_translate("Form", "---"))
        self.labelEffektElektronikk.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelEffektElektronikk.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelEffektThrustere.setText(_translate("Form", "---"))
        self.labelEffektThrustere.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelEffektThrustere.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelEffektManipulator.setText(_translate("Form", "---"))
        self.labelEffektManipulator.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelEffektManipulator.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.title_temp_ROV.setText(_translate("Form", "TEMPERATURER"))
        self.text_hovedkort.setText(_translate("Form", "Vanntemp:"))
        self.text_hovedkort.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.labelTempVann.setText(_translate("Form", "---"))
        self.labelTempVann.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTempVann.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.text_kraftkort.setText(_translate("Form", "Vanntemp MSB:"))
        self.text_kraftkort.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.text_sensorkort.setText(_translate("Form", "Sensorkort:"))
        self.text_sensorkort.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.labelTempVannMSB.setText(_translate("Form", "---"))
        self.labelTempVannMSB.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTempVannMSB.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelTempSensorkort.setText(_translate("Form", "---"))
        self.labelTempSensorkort.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTempSensorkort.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.title_motor.setText(_translate("Form", "MOTORPÅDRAG"))
        self.text_rov.setText(_translate("Form", "ROV"))
        self.text_rov.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.title_kjoremodus.setText(_translate("Form", "KJØREMODUS"))
        self.titleLys.setText(_translate("Form", "LYS"))
        self.text_lys_forward.setText(_translate("Form", "Top Light"))
        self.text_lys_forward.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.label_percentage_lys_forward.setText(_translate("Form", "<html><head/><body><span>0</span><span style=\"vertical-align:super;\">%</span></body></html>"))
        self.text_lys_down.setText(_translate("Form", "Bottom Light"))
        self.text_lys_down.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.label_percentage_lys_down.setText(_translate("Form", "<html><head/><body><span>0</span><span style=\"vertical-align:super;\">%</span></body></html>"))
        self.labelSnittTemp.setText(_translate("Form", "---"))
        self.labelSnittTemp.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelSnittTemp.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.text_gjsnitttemp.setText(_translate("Form", "Gj.snitt:"))
        self.text_gjsnitttemp.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.thrust_label_1.setText(_translate("Form", "----------"))
        self.thrust_label_5.setText(_translate("Form", "----------"))
        self.thrust_label_8.setText(_translate("Form", "----------"))
        self.thrust_label_2.setText(_translate("Form", "----------"))
        self.thrust_label_6.setText(_translate("Form", "----------"))
        self.thrust_label_7.setText(_translate("Form", "----------"))
        self.thrust_label_3.setText(_translate("Form", "----------"))
        self.thrust_label_4.setText(_translate("Form", "----------"))
        self.btnNullpunktVinkler.setText(_translate("Form", "Nullpunkt Vinkler"))
        self.btnKalibrerIMU.setText(_translate("Form", "Kalibrer IMU"))
        self.titleDybde.setText(_translate("Form", "Dybde"))
        self.btnResetManipulator.setText(_translate("Form", "Reset Manipulator "))
        self.btnResetThruster.setText(_translate("Form", "Reset Thruster"))
        self.btnReset5V.setText(_translate("Form", "Reset 5V "))
        self.title_kjoremodus_2.setText(_translate("Form", "SIKRINGER"))
        self.titleVinkler.setText(_translate("Form", "Vinkler:"))
        self.vinkel1.setText(_translate("Form", "Rull"))
        self.Vinkel2.setText(_translate("Form", "Stamp"))
        self.Vinkel3.setText(_translate("Form", "Gir"))
        self.titleAkselerasjon.setText(_translate("Form", "Akelerasjon:"))
        self.labelDybde.setText(_translate("Form", "---"))
        self.labelDybde.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelDybde.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.btnNullpunktDybde.setText(_translate("Form", "Nullpunkt Dybde"))
        self.labelRull.setText(_translate("Form", "---"))
        self.labelRull.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelRull.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelStamp.setText(_translate("Form", "---"))
        self.labelStamp.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelStamp.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelGir.setText(_translate("Form", "---"))
        self.labelGir.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelGir.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelAccel.setText(_translate("Form", "---"))
        self.labelAccel.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelAccel.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.titleNewWindow.setText(_translate("Form", "NYTT VINDU"))
        self.showNewWindowButton.setText(_translate("Form", "Show New Window"))
        self.text_sensorkort_2.setText(_translate("Form", "Sensorkort MSB:"))
        self.text_sensorkort_2.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.labelTempSensorkortMSB.setText(_translate("Form", "---"))
        self.labelTempSensorkortMSB.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTempSensorkortMSB.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.title_temp_ROV_2.setText(_translate("Form", "Alarmer"))
        self.labelLekkasjeAlarm_2.setText(_translate("Form", "---"))
        self.labelLekkasjeAlarm_2.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelLekkasjeAlarm_2.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelLekkasjeAlarm.setText(_translate("Form", "---"))
        self.labelLekkasjeAlarm.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelLekkasjeAlarm.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelIMUAlarm.setText(_translate("Form", "---"))
        self.labelIMUAlarm.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelIMUAlarm.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelTrykkAlarm.setText(_translate("Form", "---"))
        self.labelTrykkAlarm.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTrykkAlarm.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelTempAlarm.setText(_translate("Form", "---"))
        self.labelTempAlarm.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTempAlarm.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label.setText(_translate("Form", "Lekkasje:"))
        self.label_3.setText(_translate("Form", "Temp Error:"))
        self.label_2.setText(_translate("Form", "Trykk Error:"))
        self.label_4.setText(_translate("Form", "IMU Error:"))
        self.btnTakePic.setText(_translate("Form", "Screenshot"))
        self.btnRecord.setText(_translate("Form", "Record"))
