# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/dimmen/Programming/Bachelor_GUI/gui/window1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1499, 968)
        Form.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    color: #aaa;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    \n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(110, 105, 118, 255),stop:1 rgba(57, 49, 68, 255));\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background-color: #444;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    border: 1px solid #000;\n"
"    background-color: #444;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #444;\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    padding-right: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #55aaff;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolBar\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"    border: 1px solid #222;\n"
"    background-color: #333;\n"
"    color: #aaa;\n"
"\n"
"}\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(75, 165, 255, 255),stop:0.509615 rgba(119, 187, 255, 255),stop:1 rgba(72, 164, 255, 255));\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    margin-right: 2px;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(135, 206, 250, 255),stop:0.509615 rgba(176, 224, 230, 255),stop:1 rgba(135, 206, 250, 255));\n"
"}\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(65, 155, 245, 255),stop:0.509615 rgba(109, 177, 245, 255),stop:1 rgba(72, 164, 255, 255));\n"
"\n"
"}\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #9999ff;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit{\n"
"    background-color: #fff;\n"
"    color: #000;\n"
"    selection-color: #fff;\n"
"    selection-background-color: #507098;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"QTreeView\n"
"{\n"
"    background-color: #242526;\n"
"       show-decoration-selected: 0;\n"
"       selection-background-color: transparent; /* Used on Mac */\n"
"    alternate-background-color: #404040;\n"
"    selection-color: #fff; /* Used on Mac */\n"
"    font: 8pt;\n"
"    color: #fff;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"QTreeView::item\n"
"{\n"
"    border-top-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:hover\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    show-decoration-selected: 1;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    background-color: #41cd52;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:!active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-closed.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-open.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal \n"
"{\n"
"    background-color: #333;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal \n"
"{\n"
"    width: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    background-color: #333;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical \n"
"{\n"
"    height: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"")
        self.btnManuell = QtWidgets.QPushButton(Form)
        self.btnManuell.setEnabled(True)
        self.btnManuell.setGeometry(QtCore.QRect(10, 50, 541, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnManuell.sizePolicy().hasHeightForWidth())
        self.btnManuell.setSizePolicy(sizePolicy)
        self.btnManuell.setMinimumSize(QtCore.QSize(0, 0))
        self.btnManuell.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnManuell.setFont(font)
        self.btnManuell.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnManuell.setCheckable(False)
        self.btnManuell.setChecked(False)
        self.btnManuell.setAutoRepeat(False)
        self.btnManuell.setObjectName("btnManuell")
        self.btnAutonom = QtWidgets.QPushButton(Form)
        self.btnAutonom.setGeometry(QtCore.QRect(10, 100, 541, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAutonom.sizePolicy().hasHeightForWidth())
        self.btnAutonom.setSizePolicy(sizePolicy)
        self.btnAutonom.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnAutonom.setFont(font)
        self.btnAutonom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAutonom.setObjectName("btnAutonom")
        self.btnFrogCount = QtWidgets.QPushButton(Form)
        self.btnFrogCount.setGeometry(QtCore.QRect(10, 150, 541, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFrogCount.sizePolicy().hasHeightForWidth())
        self.btnFrogCount.setSizePolicy(sizePolicy)
        self.btnFrogCount.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnFrogCount.setFont(font)
        self.btnFrogCount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFrogCount.setObjectName("btnFrogCount")
        self.title_temp_ROV = QtWidgets.QLabel(Form)
        self.title_temp_ROV.setGeometry(QtCore.QRect(10, 320, 171, 18))
        self.title_temp_ROV.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_temp_ROV.setFont(font)
        self.title_temp_ROV.setTextFormat(QtCore.Qt.PlainText)
        self.title_temp_ROV.setObjectName("title_temp_ROV")
        self.text_hovedkort = QtWidgets.QLabel(Form)
        self.text_hovedkort.setGeometry(QtCore.QRect(10, 340, 113, 38))
        self.text_hovedkort.setMinimumSize(QtCore.QSize(0, 0))
        self.text_hovedkort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_hovedkort.setFont(font)
        self.text_hovedkort.setTextFormat(QtCore.Qt.PlainText)
        self.text_hovedkort.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text_hovedkort.setObjectName("text_hovedkort")
        self.labelTempVann = QtWidgets.QLabel(Form)
        self.labelTempVann.setGeometry(QtCore.QRect(130, 340, 74, 38))
        self.labelTempVann.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTempVann.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTempVann.setFont(font)
        self.labelTempVann.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelTempVann.setLineWidth(0)
        self.labelTempVann.setMidLineWidth(0)
        self.labelTempVann.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTempVann.setObjectName("labelTempVann")
        self.text_sensorkort = QtWidgets.QLabel(Form)
        self.text_sensorkort.setGeometry(QtCore.QRect(10, 380, 113, 38))
        self.text_sensorkort.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_sensorkort.setFont(font)
        self.text_sensorkort.setTextFormat(QtCore.Qt.RichText)
        self.text_sensorkort.setObjectName("text_sensorkort")
        self.labelTempSensorkort = QtWidgets.QLabel(Form)
        self.labelTempSensorkort.setGeometry(QtCore.QRect(130, 380, 74, 38))
        self.labelTempSensorkort.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTempSensorkort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTempSensorkort.setFont(font)
        self.labelTempSensorkort.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelTempSensorkort.setLineWidth(0)
        self.labelTempSensorkort.setMidLineWidth(0)
        self.labelTempSensorkort.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTempSensorkort.setObjectName("labelTempSensorkort")
        self.title_motor = QtWidgets.QLabel(Form)
        self.title_motor.setGeometry(QtCore.QRect(400, 360, 181, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_motor.setFont(font)
        self.title_motor.setObjectName("title_motor")
        self.text_rov = QtWidgets.QLabel(Form)
        self.text_rov.setGeometry(QtCore.QRect(400, 400, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_rov.setFont(font)
        self.text_rov.setStyleSheet("color: rgb(113, 126, 149);")
        self.text_rov.setLineWidth(1)
        self.text_rov.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text_rov.setObjectName("text_rov")
        self.title_kjoremodus = QtWidgets.QLabel(Form)
        self.title_kjoremodus.setGeometry(QtCore.QRect(20, 0, 371, 46))
        self.title_kjoremodus.setMinimumSize(QtCore.QSize(0, 0))
        self.title_kjoremodus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_kjoremodus.setFont(font)
        self.title_kjoremodus.setStyleSheet("")
        self.title_kjoremodus.setObjectName("title_kjoremodus")
        self.titleLys = QtWidgets.QLabel(Form)
        self.titleLys.setGeometry(QtCore.QRect(10, 680, 123, 18))
        self.titleLys.setMinimumSize(QtCore.QSize(0, 0))
        self.titleLys.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleLys.setFont(font)
        self.titleLys.setTextFormat(QtCore.Qt.PlainText)
        self.titleLys.setObjectName("titleLys")
        self.text_lys_forward = QtWidgets.QLabel(Form)
        self.text_lys_forward.setGeometry(QtCore.QRect(10, 690, 123, 68))
        self.text_lys_forward.setMinimumSize(QtCore.QSize(0, 0))
        self.text_lys_forward.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_lys_forward.setFont(font)
        self.text_lys_forward.setStyleSheet("color: rgb(113, 126, 149);")
        self.text_lys_forward.setTextFormat(QtCore.Qt.RichText)
        self.text_lys_forward.setObjectName("text_lys_forward")
        self.slider_lys_forward = QtWidgets.QSlider(Form)
        self.slider_lys_forward.setGeometry(QtCore.QRect(270, 700, 124, 68))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_lys_forward.sizePolicy().hasHeightForWidth())
        self.slider_lys_forward.setSizePolicy(sizePolicy)
        self.slider_lys_forward.setMinimumSize(QtCore.QSize(0, 68))
        self.slider_lys_forward.setMaximumSize(QtCore.QSize(16777215, 68))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.slider_lys_forward.setFont(font)
        self.slider_lys_forward.setStyleSheet("")
        self.slider_lys_forward.setMaximum(100)
        self.slider_lys_forward.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lys_forward.setInvertedAppearance(False)
        self.slider_lys_forward.setInvertedControls(False)
        self.slider_lys_forward.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_lys_forward.setTickInterval(10)
        self.slider_lys_forward.setObjectName("slider_lys_forward")
        self.label_percentage_lys_forward = QtWidgets.QLabel(Form)
        self.label_percentage_lys_forward.setGeometry(QtCore.QRect(430, 710, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_percentage_lys_forward.setFont(font)
        self.label_percentage_lys_forward.setAutoFillBackground(False)
        self.label_percentage_lys_forward.setStyleSheet("background: transparent;")
        self.label_percentage_lys_forward.setScaledContents(False)
        self.label_percentage_lys_forward.setAlignment(QtCore.Qt.AlignCenter)
        self.label_percentage_lys_forward.setWordWrap(False)
        self.label_percentage_lys_forward.setObjectName("label_percentage_lys_forward")
        self.text_lys_down = QtWidgets.QLabel(Form)
        self.text_lys_down.setGeometry(QtCore.QRect(10, 760, 123, 68))
        self.text_lys_down.setMinimumSize(QtCore.QSize(0, 0))
        self.text_lys_down.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_lys_down.setFont(font)
        self.text_lys_down.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    color: #aaa;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    \n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(110, 105, 118, 255),stop:1 rgba(57, 49, 68, 255));\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background-color: #444;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    border: 1px solid #000;\n"
"    background-color: #444;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #444;\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    padding-right: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #55aaff;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolBar\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 49, 68, 255),stop:1 rgba(110, 105, 118, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"    border: 1px solid #222;\n"
"    background-color: #333;\n"
"    color: #aaa;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(75, 165, 255, 255),stop:0.509615 rgba(119, 187, 255, 255),stop:1 rgba(72, 164, 255, 255));\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    margin-right: 2px;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(65, 155, 245, 255),stop:0.509615 rgba(109, 177, 245, 255),stop:1 rgba(72, 164, 255, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #9999ff;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit{\n"
"    background-color: #fff;\n"
"    color: #000;\n"
"    selection-color: #fff;\n"
"    selection-background-color: #507098;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"QTreeView\n"
"{\n"
"    background-color: #242526;\n"
"       show-decoration-selected: 0;\n"
"       selection-background-color: transparent; /* Used on Mac */\n"
"    alternate-background-color: #404040;\n"
"    selection-color: #fff; /* Used on Mac */\n"
"    font: 8pt;\n"
"    color: #fff;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"QTreeView::item\n"
"{\n"
"    border-top-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:hover\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    show-decoration-selected: 1;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    background-color: #41cd52;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::item:selected:!active\n"
"{\n"
"    background-color: rgba(57, 49, 68, 255);\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-closed.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings\n"
"{\n"
"    border-image: none;\n"
"    image: url(://tree-open.png); /*To replace*/\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal \n"
"{\n"
"    background-color: #333;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal \n"
"{\n"
"    width: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    background-color: #333;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    border: 1px solid #111;\n"
"    background-color: #535353;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical \n"
"{\n"
"    height: 0px;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"")
        self.text_lys_down.setTextFormat(QtCore.Qt.RichText)
        self.text_lys_down.setObjectName("text_lys_down")
        self.slider_lys_down = QtWidgets.QSlider(Form)
        self.slider_lys_down.setGeometry(QtCore.QRect(270, 780, 124, 68))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_lys_down.sizePolicy().hasHeightForWidth())
        self.slider_lys_down.setSizePolicy(sizePolicy)
        self.slider_lys_down.setMinimumSize(QtCore.QSize(0, 68))
        self.slider_lys_down.setMaximumSize(QtCore.QSize(16777215, 68))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.slider_lys_down.setFont(font)
        self.slider_lys_down.setStyleSheet("")
        self.slider_lys_down.setMaximum(100)
        self.slider_lys_down.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lys_down.setInvertedAppearance(False)
        self.slider_lys_down.setInvertedControls(False)
        self.slider_lys_down.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_lys_down.setTickInterval(10)
        self.slider_lys_down.setObjectName("slider_lys_down")
        self.label_percentage_lys_down = QtWidgets.QLabel(Form)
        self.label_percentage_lys_down.setGeometry(QtCore.QRect(430, 790, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_percentage_lys_down.setFont(font)
        self.label_percentage_lys_down.setAutoFillBackground(False)
        self.label_percentage_lys_down.setStyleSheet("background: transparent;")
        self.label_percentage_lys_down.setScaledContents(False)
        self.label_percentage_lys_down.setAlignment(QtCore.Qt.AlignCenter)
        self.label_percentage_lys_down.setWordWrap(False)
        self.label_percentage_lys_down.setObjectName("label_percentage_lys_down")
        self.thrust_label_1 = QtWidgets.QLabel(Form)
        self.thrust_label_1.setGeometry(QtCore.QRect(270, 450, 61, 51))
        self.thrust_label_1.setObjectName("thrust_label_1")
        self.thrust_label_5 = QtWidgets.QLabel(Form)
        self.thrust_label_5.setGeometry(QtCore.QRect(270, 500, 61, 51))
        self.thrust_label_5.setObjectName("thrust_label_5")
        self.thrust_label_8 = QtWidgets.QLabel(Form)
        self.thrust_label_8.setGeometry(QtCore.QRect(630, 500, 61, 51))
        self.thrust_label_8.setObjectName("thrust_label_8")
        self.thrust_label_2 = QtWidgets.QLabel(Form)
        self.thrust_label_2.setGeometry(QtCore.QRect(350, 450, 61, 51))
        self.thrust_label_2.setObjectName("thrust_label_2")
        self.thrust_label_6 = QtWidgets.QLabel(Form)
        self.thrust_label_6.setGeometry(QtCore.QRect(350, 500, 61, 51))
        self.thrust_label_6.setObjectName("thrust_label_6")
        self.thrust_label_7 = QtWidgets.QLabel(Form)
        self.thrust_label_7.setGeometry(QtCore.QRect(550, 500, 61, 51))
        self.thrust_label_7.setObjectName("thrust_label_7")
        self.thrust_label_3 = QtWidgets.QLabel(Form)
        self.thrust_label_3.setGeometry(QtCore.QRect(550, 450, 61, 51))
        self.thrust_label_3.setObjectName("thrust_label_3")
        self.thrust_label_4 = QtWidgets.QLabel(Form)
        self.thrust_label_4.setGeometry(QtCore.QRect(630, 450, 61, 51))
        self.thrust_label_4.setObjectName("thrust_label_4")
        self.btnNullpunktVinkler = QtWidgets.QPushButton(Form)
        self.btnNullpunktVinkler.setGeometry(QtCore.QRect(1350, 80, 111, 161))
        self.btnNullpunktVinkler.setObjectName("btnNullpunktVinkler")
        self.btnResetManipulator = QtWidgets.QPushButton(Form)
        self.btnResetManipulator.setGeometry(QtCore.QRect(560, 230, 301, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResetManipulator.sizePolicy().hasHeightForWidth())
        self.btnResetManipulator.setSizePolicy(sizePolicy)
        self.btnResetManipulator.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnResetManipulator.setFont(font)
        self.btnResetManipulator.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResetManipulator.setObjectName("btnResetManipulator")
        self.btnResetThruster = QtWidgets.QPushButton(Form)
        self.btnResetThruster.setGeometry(QtCore.QRect(560, 140, 301, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResetThruster.sizePolicy().hasHeightForWidth())
        self.btnResetThruster.setSizePolicy(sizePolicy)
        self.btnResetThruster.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnResetThruster.setFont(font)
        self.btnResetThruster.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResetThruster.setObjectName("btnResetThruster")
        self.btnReset5V = QtWidgets.QPushButton(Form)
        self.btnReset5V.setGeometry(QtCore.QRect(560, 50, 301, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReset5V.sizePolicy().hasHeightForWidth())
        self.btnReset5V.setSizePolicy(sizePolicy)
        self.btnReset5V.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnReset5V.setFont(font)
        self.btnReset5V.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReset5V.setObjectName("btnReset5V")
        self.title_kjoremodus_2 = QtWidgets.QLabel(Form)
        self.title_kjoremodus_2.setGeometry(QtCore.QRect(560, 0, 291, 46))
        self.title_kjoremodus_2.setMinimumSize(QtCore.QSize(0, 0))
        self.title_kjoremodus_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_kjoremodus_2.setFont(font)
        self.title_kjoremodus_2.setStyleSheet("")
        self.title_kjoremodus_2.setObjectName("title_kjoremodus_2")
        self.titleVinkler = QtWidgets.QLabel(Form)
        self.titleVinkler.setGeometry(QtCore.QRect(1170, 80, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleVinkler.setFont(font)
        self.titleVinkler.setObjectName("titleVinkler")
        self.vinkel1 = QtWidgets.QLabel(Form)
        self.vinkel1.setGeometry(QtCore.QRect(1160, 120, 47, 13))
        self.vinkel1.setObjectName("vinkel1")
        self.Vinkel2 = QtWidgets.QLabel(Form)
        self.Vinkel2.setGeometry(QtCore.QRect(1160, 170, 47, 13))
        self.Vinkel2.setObjectName("Vinkel2")
        self.Vinkel3 = QtWidgets.QLabel(Form)
        self.Vinkel3.setGeometry(QtCore.QRect(1160, 210, 81, 21))
        self.Vinkel3.setObjectName("Vinkel3")
        self.labelRull = QtWidgets.QLabel(Form)
        self.labelRull.setGeometry(QtCore.QRect(1260, 110, 74, 42))
        self.labelRull.setMinimumSize(QtCore.QSize(0, 0))
        self.labelRull.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRull.setFont(font)
        self.labelRull.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelRull.setLineWidth(0)
        self.labelRull.setMidLineWidth(0)
        self.labelRull.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRull.setObjectName("labelRull")
        self.labelStamp = QtWidgets.QLabel(Form)
        self.labelStamp.setGeometry(QtCore.QRect(1260, 150, 74, 42))
        self.labelStamp.setMinimumSize(QtCore.QSize(0, 0))
        self.labelStamp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelStamp.setFont(font)
        self.labelStamp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStamp.setLineWidth(0)
        self.labelStamp.setMidLineWidth(0)
        self.labelStamp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStamp.setObjectName("labelStamp")
        self.labelGir = QtWidgets.QLabel(Form)
        self.labelGir.setGeometry(QtCore.QRect(1260, 190, 74, 42))
        self.labelGir.setMinimumSize(QtCore.QSize(0, 0))
        self.labelGir.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelGir.setFont(font)
        self.labelGir.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelGir.setLineWidth(0)
        self.labelGir.setMidLineWidth(0)
        self.labelGir.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGir.setObjectName("labelGir")
        self.showNewWindowButton = QtWidgets.QPushButton(Form)
        self.showNewWindowButton.setGeometry(QtCore.QRect(380, 250, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showNewWindowButton.sizePolicy().hasHeightForWidth())
        self.showNewWindowButton.setSizePolicy(sizePolicy)
        self.showNewWindowButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.showNewWindowButton.setFont(font)
        self.showNewWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showNewWindowButton.setObjectName("showNewWindowButton")
        self.title_temp_ROV_2 = QtWidgets.QLabel(Form)
        self.title_temp_ROV_2.setGeometry(QtCore.QRect(870, 510, 191, 20))
        self.title_temp_ROV_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_temp_ROV_2.setFont(font)
        self.title_temp_ROV_2.setTextFormat(QtCore.Qt.PlainText)
        self.title_temp_ROV_2.setObjectName("title_temp_ROV_2")
        self.labelLekkasjeAlarm = QtWidgets.QLabel(Form)
        self.labelLekkasjeAlarm.setGeometry(QtCore.QRect(1010, 540, 101, 31))
        self.labelLekkasjeAlarm.setMinimumSize(QtCore.QSize(0, 0))
        self.labelLekkasjeAlarm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLekkasjeAlarm.setFont(font)
        self.labelLekkasjeAlarm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelLekkasjeAlarm.setLineWidth(0)
        self.labelLekkasjeAlarm.setMidLineWidth(0)
        self.labelLekkasjeAlarm.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLekkasjeAlarm.setObjectName("labelLekkasjeAlarm")
        self.labelIMUAlarm = QtWidgets.QLabel(Form)
        self.labelIMUAlarm.setGeometry(QtCore.QRect(1020, 680, 81, 31))
        self.labelIMUAlarm.setMinimumSize(QtCore.QSize(0, 0))
        self.labelIMUAlarm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelIMUAlarm.setFont(font)
        self.labelIMUAlarm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelIMUAlarm.setLineWidth(0)
        self.labelIMUAlarm.setMidLineWidth(0)
        self.labelIMUAlarm.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIMUAlarm.setObjectName("labelIMUAlarm")
        self.labelTrykkAlarm = QtWidgets.QLabel(Form)
        self.labelTrykkAlarm.setGeometry(QtCore.QRect(1020, 580, 81, 31))
        self.labelTrykkAlarm.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTrykkAlarm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTrykkAlarm.setFont(font)
        self.labelTrykkAlarm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelTrykkAlarm.setLineWidth(0)
        self.labelTrykkAlarm.setMidLineWidth(0)
        self.labelTrykkAlarm.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTrykkAlarm.setObjectName("labelTrykkAlarm")
        self.labelTempAlarm = QtWidgets.QLabel(Form)
        self.labelTempAlarm.setGeometry(QtCore.QRect(1000, 620, 111, 41))
        self.labelTempAlarm.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTempAlarm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTempAlarm.setFont(font)
        self.labelTempAlarm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelTempAlarm.setLineWidth(0)
        self.labelTempAlarm.setMidLineWidth(0)
        self.labelTempAlarm.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTempAlarm.setObjectName("labelTempAlarm")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(870, 540, 129, 43))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(870, 630, 61, 41))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(870, 580, 61, 51))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(870, 670, 91, 41))
        self.label_4.setObjectName("label_4")
        self.btnTakePic = QtWidgets.QPushButton(Form)
        self.btnTakePic.setGeometry(QtCore.QRect(10, 250, 161, 51))
        self.btnTakePic.setObjectName("btnTakePic")
        self.btnRecord = QtWidgets.QPushButton(Form)
        self.btnRecord.setGeometry(QtCore.QRect(170, 250, 211, 51))
        self.btnRecord.setObjectName("btnRecord")
        self.btnOpenCamera = QtWidgets.QPushButton(Form)
        self.btnOpenCamera.setGeometry(QtCore.QRect(10, 200, 541, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenCamera.sizePolicy().hasHeightForWidth())
        self.btnOpenCamera.setSizePolicy(sizePolicy)
        self.btnOpenCamera.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnOpenCamera.setFont(font)
        self.btnOpenCamera.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOpenCamera.setObjectName("btnOpenCamera")
        self.btnTopLys = QtWidgets.QPushButton(Form)
        self.btnTopLys.setGeometry(QtCore.QRect(140, 710, 93, 28))
        self.btnTopLys.setObjectName("btnTopLys")
        self.btnBunnLys = QtWidgets.QPushButton(Form)
        self.btnBunnLys.setGeometry(QtCore.QRect(140, 780, 93, 28))
        self.btnBunnLys.setObjectName("btnBunnLys")
        self.btnKalibrerIMU = QtWidgets.QPushButton(Form)
        self.btnKalibrerIMU.setGeometry(QtCore.QRect(50, 890, 111, 51))
        self.btnKalibrerIMU.setObjectName("btnKalibrerIMU")
        self.title_kjoremodus_3 = QtWidgets.QLabel(Form)
        self.title_kjoremodus_3.setGeometry(QtCore.QRect(870, 0, 101, 46))
        self.title_kjoremodus_3.setMinimumSize(QtCore.QSize(0, 0))
        self.title_kjoremodus_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_kjoremodus_3.setFont(font)
        self.title_kjoremodus_3.setStyleSheet("")
        self.title_kjoremodus_3.setObjectName("title_kjoremodus_3")
        self.btnRegOn = QtWidgets.QPushButton(Form)
        self.btnRegOn.setEnabled(True)
        self.btnRegOn.setGeometry(QtCore.QRect(870, 50, 281, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRegOn.sizePolicy().hasHeightForWidth())
        self.btnRegOn.setSizePolicy(sizePolicy)
        self.btnRegOn.setMinimumSize(QtCore.QSize(0, 0))
        self.btnRegOn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnRegOn.setFont(font)
        self.btnRegOn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRegOn.setCheckable(False)
        self.btnRegOn.setChecked(False)
        self.btnRegOn.setAutoRepeat(False)
        self.btnRegOn.setObjectName("btnRegOn")
        self.btnRullOn = QtWidgets.QPushButton(Form)
        self.btnRullOn.setEnabled(True)
        self.btnRullOn.setGeometry(QtCore.QRect(870, 100, 281, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRullOn.sizePolicy().hasHeightForWidth())
        self.btnRullOn.setSizePolicy(sizePolicy)
        self.btnRullOn.setMinimumSize(QtCore.QSize(0, 0))
        self.btnRullOn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnRullOn.setFont(font)
        self.btnRullOn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRullOn.setCheckable(False)
        self.btnRullOn.setChecked(False)
        self.btnRullOn.setAutoRepeat(False)
        self.btnRullOn.setObjectName("btnRullOn")
        self.btnStampOn = QtWidgets.QPushButton(Form)
        self.btnStampOn.setEnabled(True)
        self.btnStampOn.setGeometry(QtCore.QRect(870, 150, 281, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStampOn.sizePolicy().hasHeightForWidth())
        self.btnStampOn.setSizePolicy(sizePolicy)
        self.btnStampOn.setMinimumSize(QtCore.QSize(0, 0))
        self.btnStampOn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnStampOn.setFont(font)
        self.btnStampOn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStampOn.setCheckable(False)
        self.btnStampOn.setChecked(False)
        self.btnStampOn.setAutoRepeat(False)
        self.btnStampOn.setObjectName("btnStampOn")
        self.btnDybdeOn = QtWidgets.QPushButton(Form)
        self.btnDybdeOn.setEnabled(True)
        self.btnDybdeOn.setGeometry(QtCore.QRect(870, 200, 281, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDybdeOn.sizePolicy().hasHeightForWidth())
        self.btnDybdeOn.setSizePolicy(sizePolicy)
        self.btnDybdeOn.setMinimumSize(QtCore.QSize(0, 0))
        self.btnDybdeOn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnDybdeOn.setFont(font)
        self.btnDybdeOn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDybdeOn.setCheckable(False)
        self.btnDybdeOn.setChecked(False)
        self.btnDybdeOn.setAutoRepeat(False)
        self.btnDybdeOn.setObjectName("btnDybdeOn")
        self.btnRegTuning = QtWidgets.QPushButton(Form)
        self.btnRegTuning.setGeometry(QtCore.QRect(1050, 290, 101, 31))
        self.btnRegTuning.setObjectName("btnRegTuning")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(870, 260, 191, 16))
        self.label_5.setObjectName("label_5")
        self.btnKalibrerIMU_2 = QtWidgets.QPushButton(Form)
        self.btnKalibrerIMU_2.setGeometry(QtCore.QRect(210, 890, 81, 51))
        self.btnKalibrerIMU_2.setObjectName("btnKalibrerIMU_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(210, 870, 191, 16))
        self.label_8.setObjectName("label_8")
        self.labelVanntype = QtWidgets.QLabel(Form)
        self.labelVanntype.setGeometry(QtCore.QRect(290, 890, 91, 51))
        self.labelVanntype.setMinimumSize(QtCore.QSize(0, 0))
        self.labelVanntype.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelVanntype.setFont(font)
        self.labelVanntype.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelVanntype.setLineWidth(0)
        self.labelVanntype.setMidLineWidth(0)
        self.labelVanntype.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVanntype.setObjectName("labelVanntype")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(530, 690, 141, 17))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(860, 720, 131, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 430, 121, 17))
        self.label_12.setObjectName("label_12")
        self.labelManipulatorKraft = QtWidgets.QLabel(Form)
        self.labelManipulatorKraft.setGeometry(QtCore.QRect(690, 680, 74, 42))
        self.labelManipulatorKraft.setMinimumSize(QtCore.QSize(0, 0))
        self.labelManipulatorKraft.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelManipulatorKraft.setFont(font)
        self.labelManipulatorKraft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelManipulatorKraft.setLineWidth(0)
        self.labelManipulatorKraft.setMidLineWidth(0)
        self.labelManipulatorKraft.setAlignment(QtCore.Qt.AlignCenter)
        self.labelManipulatorKraft.setObjectName("labelManipulatorKraft")
        self.labelManipulatorTemp = QtWidgets.QLabel(Form)
        self.labelManipulatorTemp.setGeometry(QtCore.QRect(130, 420, 74, 42))
        self.labelManipulatorTemp.setMinimumSize(QtCore.QSize(0, 0))
        self.labelManipulatorTemp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelManipulatorTemp.setFont(font)
        self.labelManipulatorTemp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelManipulatorTemp.setLineWidth(0)
        self.labelManipulatorTemp.setMidLineWidth(0)
        self.labelManipulatorTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelManipulatorTemp.setObjectName("labelManipulatorTemp")
        self.labelManipulatorSikring = QtWidgets.QLabel(Form)
        self.labelManipulatorSikring.setGeometry(QtCore.QRect(1000, 710, 161, 42))
        self.labelManipulatorSikring.setMinimumSize(QtCore.QSize(0, 0))
        self.labelManipulatorSikring.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelManipulatorSikring.setFont(font)
        self.labelManipulatorSikring.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelManipulatorSikring.setLineWidth(0)
        self.labelManipulatorSikring.setMidLineWidth(0)
        self.labelManipulatorSikring.setAlignment(QtCore.Qt.AlignCenter)
        self.labelManipulatorSikring.setObjectName("labelManipulatorSikring")
        self.titleDybde = QtWidgets.QLabel(Form)
        self.titleDybde.setGeometry(QtCore.QRect(470, 930, 51, 18))
        self.titleDybde.setMinimumSize(QtCore.QSize(0, 0))
        self.titleDybde.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleDybde.setFont(font)
        self.titleDybde.setStyleSheet("")
        self.titleDybde.setObjectName("titleDybde")
        self.btnNullpunktDybde = QtWidgets.QPushButton(Form)
        self.btnNullpunktDybde.setGeometry(QtCore.QRect(640, 910, 111, 51))
        self.btnNullpunktDybde.setObjectName("btnNullpunktDybde")
        self.labelDybde = QtWidgets.QLabel(Form)
        self.labelDybde.setGeometry(QtCore.QRect(550, 920, 74, 42))
        self.labelDybde.setMinimumSize(QtCore.QSize(0, 0))
        self.labelDybde.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelDybde.setFont(font)
        self.labelDybde.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelDybde.setLineWidth(0)
        self.labelDybde.setMidLineWidth(0)
        self.labelDybde.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDybde.setObjectName("labelDybde")
        self.text_sensorkort_2 = QtWidgets.QLabel(Form)
        self.text_sensorkort_2.setGeometry(QtCore.QRect(10, 460, 113, 38))
        self.text_sensorkort_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_sensorkort_2.setFont(font)
        self.text_sensorkort_2.setTextFormat(QtCore.Qt.RichText)
        self.text_sensorkort_2.setObjectName("text_sensorkort_2")
        self.text_sensorkort_3 = QtWidgets.QLabel(Form)
        self.text_sensorkort_3.setGeometry(QtCore.QRect(10, 490, 113, 38))
        self.text_sensorkort_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_sensorkort_3.setFont(font)
        self.text_sensorkort_3.setTextFormat(QtCore.Qt.RichText)
        self.text_sensorkort_3.setObjectName("text_sensorkort_3")
        self.text_sensorkort_4 = QtWidgets.QLabel(Form)
        self.text_sensorkort_4.setGeometry(QtCore.QRect(0, 530, 113, 38))
        self.text_sensorkort_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_sensorkort_4.setFont(font)
        self.text_sensorkort_4.setTextFormat(QtCore.Qt.RichText)
        self.text_sensorkort_4.setObjectName("text_sensorkort_4")
        self.labelThruster12VTemp = QtWidgets.QLabel(Form)
        self.labelThruster12VTemp.setGeometry(QtCore.QRect(130, 450, 74, 42))
        self.labelThruster12VTemp.setMinimumSize(QtCore.QSize(0, 0))
        self.labelThruster12VTemp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelThruster12VTemp.setFont(font)
        self.labelThruster12VTemp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelThruster12VTemp.setLineWidth(0)
        self.labelThruster12VTemp.setMidLineWidth(0)
        self.labelThruster12VTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelThruster12VTemp.setObjectName("labelThruster12VTemp")
        self.labelKraft5VTemp = QtWidgets.QLabel(Form)
        self.labelKraft5VTemp.setGeometry(QtCore.QRect(130, 480, 74, 42))
        self.labelKraft5VTemp.setMinimumSize(QtCore.QSize(0, 0))
        self.labelKraft5VTemp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelKraft5VTemp.setFont(font)
        self.labelKraft5VTemp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelKraft5VTemp.setLineWidth(0)
        self.labelKraft5VTemp.setMidLineWidth(0)
        self.labelKraft5VTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelKraft5VTemp.setObjectName("labelKraft5VTemp")
        self.labelTempKomKontroller = QtWidgets.QLabel(Form)
        self.labelTempKomKontroller.setGeometry(QtCore.QRect(130, 520, 74, 42))
        self.labelTempKomKontroller.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTempKomKontroller.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTempKomKontroller.setFont(font)
        self.labelTempKomKontroller.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelTempKomKontroller.setLineWidth(0)
        self.labelTempKomKontroller.setMidLineWidth(0)
        self.labelTempKomKontroller.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTempKomKontroller.setObjectName("labelTempKomKontroller")
        self.Motordriver = QtWidgets.QLabel(Form)
        self.Motordriver.setGeometry(QtCore.QRect(10, 560, 113, 38))
        self.Motordriver.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Motordriver.setFont(font)
        self.Motordriver.setTextFormat(QtCore.Qt.RichText)
        self.Motordriver.setObjectName("Motordriver")
        self.labelMotorTemp = QtWidgets.QLabel(Form)
        self.labelMotorTemp.setGeometry(QtCore.QRect(130, 560, 74, 42))
        self.labelMotorTemp.setMinimumSize(QtCore.QSize(0, 0))
        self.labelMotorTemp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMotorTemp.setFont(font)
        self.labelMotorTemp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelMotorTemp.setLineWidth(0)
        self.labelMotorTemp.setMidLineWidth(0)
        self.labelMotorTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMotorTemp.setObjectName("labelMotorTemp")
        self.title_temp_ROV_3 = QtWidgets.QLabel(Form)
        self.title_temp_ROV_3.setGeometry(QtCore.QRect(530, 650, 171, 18))
        self.title_temp_ROV_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_temp_ROV_3.setFont(font)
        self.title_temp_ROV_3.setTextFormat(QtCore.Qt.PlainText)
        self.title_temp_ROV_3.setObjectName("title_temp_ROV_3")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(530, 720, 141, 17))
        self.label_10.setObjectName("label_10")
        self.text_sensorkort_5 = QtWidgets.QLabel(Form)
        self.text_sensorkort_5.setGeometry(QtCore.QRect(530, 740, 113, 38))
        self.text_sensorkort_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_sensorkort_5.setFont(font)
        self.text_sensorkort_5.setTextFormat(QtCore.Qt.RichText)
        self.text_sensorkort_5.setObjectName("text_sensorkort_5")
        self.labelThrusterKraft = QtWidgets.QLabel(Form)
        self.labelThrusterKraft.setGeometry(QtCore.QRect(690, 710, 74, 42))
        self.labelThrusterKraft.setMinimumSize(QtCore.QSize(0, 0))
        self.labelThrusterKraft.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelThrusterKraft.setFont(font)
        self.labelThrusterKraft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelThrusterKraft.setLineWidth(0)
        self.labelThrusterKraft.setMidLineWidth(0)
        self.labelThrusterKraft.setAlignment(QtCore.Qt.AlignCenter)
        self.labelThrusterKraft.setObjectName("labelThrusterKraft")
        self.labelKraft5V = QtWidgets.QLabel(Form)
        self.labelKraft5V.setGeometry(QtCore.QRect(690, 750, 74, 42))
        self.labelKraft5V.setMinimumSize(QtCore.QSize(0, 0))
        self.labelKraft5V.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelKraft5V.setFont(font)
        self.labelKraft5V.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelKraft5V.setLineWidth(0)
        self.labelKraft5V.setMidLineWidth(0)
        self.labelKraft5V.setAlignment(QtCore.Qt.AlignCenter)
        self.labelKraft5V.setObjectName("labelKraft5V")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(860, 770, 131, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(860, 800, 131, 17))
        self.label_14.setObjectName("label_14")
        self.labelThrusterSikring = QtWidgets.QLabel(Form)
        self.labelThrusterSikring.setGeometry(QtCore.QRect(1000, 750, 161, 42))
        self.labelThrusterSikring.setMinimumSize(QtCore.QSize(0, 0))
        self.labelThrusterSikring.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelThrusterSikring.setFont(font)
        self.labelThrusterSikring.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelThrusterSikring.setLineWidth(0)
        self.labelThrusterSikring.setMidLineWidth(0)
        self.labelThrusterSikring.setAlignment(QtCore.Qt.AlignCenter)
        self.labelThrusterSikring.setObjectName("labelThrusterSikring")
        self.labelKraftSikring = QtWidgets.QLabel(Form)
        self.labelKraftSikring.setGeometry(QtCore.QRect(990, 790, 161, 42))
        self.labelKraftSikring.setMinimumSize(QtCore.QSize(0, 0))
        self.labelKraftSikring.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelKraftSikring.setFont(font)
        self.labelKraftSikring.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelKraftSikring.setLineWidth(0)
        self.labelKraftSikring.setMidLineWidth(0)
        self.labelKraftSikring.setAlignment(QtCore.Qt.AlignCenter)
        self.labelKraftSikring.setObjectName("labelKraftSikring")
        self.Motordriver_2 = QtWidgets.QLabel(Form)
        self.Motordriver_2.setGeometry(QtCore.QRect(10, 600, 113, 38))
        self.Motordriver_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Motordriver_2.setFont(font)
        self.Motordriver_2.setTextFormat(QtCore.Qt.RichText)
        self.Motordriver_2.setObjectName("Motordriver_2")
        self.labelReguleringTemp = QtWidgets.QLabel(Form)
        self.labelReguleringTemp.setGeometry(QtCore.QRect(130, 600, 74, 42))
        self.labelReguleringTemp.setMinimumSize(QtCore.QSize(0, 0))
        self.labelReguleringTemp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelReguleringTemp.setFont(font)
        self.labelReguleringTemp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelReguleringTemp.setLineWidth(0)
        self.labelReguleringTemp.setMidLineWidth(0)
        self.labelReguleringTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReguleringTemp.setObjectName("labelReguleringTemp")
        self.tuningInput = QtWidgets.QLineEdit(Form)
        self.tuningInput.setGeometry(QtCore.QRect(980, 290, 51, 31))
        self.tuningInput.setText("")
        self.tuningInput.setObjectName("tuningInput")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(720, 310, 101, 191))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.reguleringDropdown = QtWidgets.QComboBox(Form)
        self.reguleringDropdown.setGeometry(QtCore.QRect(880, 290, 86, 25))
        self.reguleringDropdown.setObjectName("reguleringDropdown")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")
        self.reguleringDropdown.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnManuell.setText(_translate("Form", "Manuell kjøring"))
        self.btnAutonom.setText(_translate("Form", "Autonom docking"))
        self.btnFrogCount.setText(_translate("Form", "Start Frog Count"))
        self.title_temp_ROV.setText(_translate("Form", "TEMPERATURER"))
        self.text_hovedkort.setText(_translate("Form", "Vanntemp:"))
        self.text_hovedkort.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.labelTempVann.setText(_translate("Form", "---"))
        self.labelTempVann.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTempVann.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.text_sensorkort.setText(_translate("Form", "Sensorkort:"))
        self.text_sensorkort.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.labelTempSensorkort.setText(_translate("Form", "---"))
        self.labelTempSensorkort.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTempSensorkort.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.title_motor.setText(_translate("Form", "MOTORPÅDRAG"))
        self.text_rov.setText(_translate("Form", "ROV"))
        self.text_rov.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.title_kjoremodus.setText(_translate("Form", "KJØREMODUS OG KAMERA"))
        self.titleLys.setText(_translate("Form", "LYS"))
        self.text_lys_forward.setText(_translate("Form", "Top Light"))
        self.text_lys_forward.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.label_percentage_lys_forward.setText(_translate("Form", "<html><head/><body><span>0</span><span style=\"vertical-align:super;\">%</span></body></html>"))
        self.text_lys_down.setText(_translate("Form", "Bottom Light"))
        self.text_lys_down.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.label_percentage_lys_down.setText(_translate("Form", "<html><head/><body><span>0</span><span style=\"vertical-align:super;\">%</span></body></html>"))
        self.thrust_label_1.setText(_translate("Form", "----------"))
        self.thrust_label_5.setText(_translate("Form", "----------"))
        self.thrust_label_8.setText(_translate("Form", "----------"))
        self.thrust_label_2.setText(_translate("Form", "----------"))
        self.thrust_label_6.setText(_translate("Form", "----------"))
        self.thrust_label_7.setText(_translate("Form", "----------"))
        self.thrust_label_3.setText(_translate("Form", "----------"))
        self.thrust_label_4.setText(_translate("Form", "----------"))
        self.btnNullpunktVinkler.setText(_translate("Form", "Nullpunkt Vinkler"))
        self.btnResetManipulator.setText(_translate("Form", "Reset Manipulator "))
        self.btnResetThruster.setText(_translate("Form", "Reset Thruster"))
        self.btnReset5V.setText(_translate("Form", "Reset 5V "))
        self.title_kjoremodus_2.setText(_translate("Form", "SIKRINGER"))
        self.titleVinkler.setText(_translate("Form", "Vinkler:"))
        self.vinkel1.setText(_translate("Form", "Rull"))
        self.Vinkel2.setText(_translate("Form", "Stamp"))
        self.Vinkel3.setText(_translate("Form", "Gir"))
        self.labelRull.setText(_translate("Form", "---"))
        self.labelRull.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelRull.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelStamp.setText(_translate("Form", "---"))
        self.labelStamp.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelStamp.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelGir.setText(_translate("Form", "---"))
        self.labelGir.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelGir.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.showNewWindowButton.setText(_translate("Form", "Open Pictures"))
        self.title_temp_ROV_2.setText(_translate("Form", "Alarmer"))
        self.labelLekkasjeAlarm.setText(_translate("Form", "---"))
        self.labelLekkasjeAlarm.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelLekkasjeAlarm.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelIMUAlarm.setText(_translate("Form", "---"))
        self.labelIMUAlarm.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelIMUAlarm.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelTrykkAlarm.setText(_translate("Form", "---"))
        self.labelTrykkAlarm.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTrykkAlarm.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelTempAlarm.setText(_translate("Form", "---"))
        self.labelTempAlarm.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTempAlarm.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label.setText(_translate("Form", "Lekkasje:"))
        self.label_3.setText(_translate("Form", "Temp Error:"))
        self.label_2.setText(_translate("Form", "Trykk Error:"))
        self.label_4.setText(_translate("Form", "IMU Error:"))
        self.btnTakePic.setText(_translate("Form", "Screenshot"))
        self.btnRecord.setText(_translate("Form", "Record"))
        self.btnOpenCamera.setText(_translate("Form", "Open Camera"))
        self.btnTopLys.setText(_translate("Form", "På/Av"))
        self.btnBunnLys.setText(_translate("Form", "På/Av"))
        self.btnKalibrerIMU.setText(_translate("Form", "Kalibrer_IMU"))
        self.title_kjoremodus_3.setText(_translate("Form", "Regulering"))
        self.btnRegOn.setText(_translate("Form", "All regulering"))
        self.btnRullOn.setText(_translate("Form", "Rull reg på"))
        self.btnStampOn.setText(_translate("Form", "Stamp reg på"))
        self.btnDybdeOn.setText(_translate("Form", "Dybde reg på"))
        self.btnRegTuning.setText(_translate("Form", "Submit"))
        self.label_5.setText(_translate("Form", "Regulator tuning"))
        self.btnKalibrerIMU_2.setText(_translate("Form", "---"))
        self.label_8.setText(_translate("Form", "Vanntype Salt/Ferskvatn"))
        self.labelVanntype.setText(_translate("Form", "---"))
        self.labelVanntype.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelVanntype.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label_9.setText(_translate("Form", "Manipulator"))
        self.label_11.setText(_translate("Form", "ManipulatorFuse"))
        self.label_12.setText(_translate("Form", "Manipulator12V"))
        self.labelManipulatorKraft.setText(_translate("Form", "---"))
        self.labelManipulatorKraft.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelManipulatorKraft.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelManipulatorTemp.setText(_translate("Form", "---"))
        self.labelManipulatorTemp.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelManipulatorTemp.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelManipulatorSikring.setText(_translate("Form", "---"))
        self.labelManipulatorSikring.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelManipulatorSikring.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.titleDybde.setText(_translate("Form", "Dybde"))
        self.btnNullpunktDybde.setText(_translate("Form", "Nullpunkt Dybde"))
        self.labelDybde.setText(_translate("Form", "---"))
        self.labelDybde.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelDybde.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.text_sensorkort_2.setText(_translate("Form", "Thruster12V"))
        self.text_sensorkort_2.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.text_sensorkort_3.setText(_translate("Form", "Kraft5V"))
        self.text_sensorkort_3.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.text_sensorkort_4.setText(_translate("Form", "KomKontroller"))
        self.text_sensorkort_4.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.labelThruster12VTemp.setText(_translate("Form", "---"))
        self.labelThruster12VTemp.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelThruster12VTemp.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelKraft5VTemp.setText(_translate("Form", "---"))
        self.labelKraft5VTemp.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelKraft5VTemp.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelTempKomKontroller.setText(_translate("Form", "---"))
        self.labelTempKomKontroller.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelTempKomKontroller.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.Motordriver.setText(_translate("Form", "Motordriver"))
        self.Motordriver.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.labelMotorTemp.setText(_translate("Form", "---"))
        self.labelMotorTemp.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelMotorTemp.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.title_temp_ROV_3.setText(_translate("Form", "Kraft"))
        self.label_10.setText(_translate("Form", "Thruster"))
        self.text_sensorkort_5.setText(_translate("Form", "Kraft5V"))
        self.text_sensorkort_5.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.labelThrusterKraft.setText(_translate("Form", "---"))
        self.labelThrusterKraft.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelThrusterKraft.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelKraft5V.setText(_translate("Form", "---"))
        self.labelKraft5V.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelKraft5V.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.label_13.setText(_translate("Form", "ThrusterFuse"))
        self.label_14.setText(_translate("Form", "KraftFuse"))
        self.labelThrusterSikring.setText(_translate("Form", "---"))
        self.labelThrusterSikring.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelThrusterSikring.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.labelKraftSikring.setText(_translate("Form", "---"))
        self.labelKraftSikring.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelKraftSikring.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        self.Motordriver_2.setText(_translate("Form", "Regulering"))
        self.Motordriver_2.setProperty("colorStyle", _translate("Form", "subTitle"))
        self.labelReguleringTemp.setText(_translate("Form", "---"))
        self.labelReguleringTemp.setProperty("labelStyle", _translate("Form", "blackBg"))
        self.labelReguleringTemp.setProperty("labelStyle2", _translate("Form", "whiteBg"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "Rull KP"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "Rull KI"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "Rull KD"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "Stamp KP"))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", "Stamp KI"))
        item = self.listWidget.item(5)
        item.setText(_translate("Form", "Stamp KD"))
        item = self.listWidget.item(6)
        item.setText(_translate("Form", "Dybde KP"))
        item = self.listWidget.item(7)
        item.setText(_translate("Form", "Dybde KI"))
        item = self.listWidget.item(8)
        item.setText(_translate("Form", "Dybde KD"))
        item = self.listWidget.item(9)
        item.setText(_translate("Form", "TS"))
        item = self.listWidget.item(10)
        item.setText(_translate("Form", "Alpha"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.reguleringDropdown.setItemText(0, _translate("Form", "Rull KI"))
        self.reguleringDropdown.setItemText(1, _translate("Form", "Rull KD"))
        self.reguleringDropdown.setItemText(2, _translate("Form", "Rull KP"))
        self.reguleringDropdown.setItemText(3, _translate("Form", "Stamp KI"))
        self.reguleringDropdown.setItemText(4, _translate("Form", "Stamp KD"))
        self.reguleringDropdown.setItemText(5, _translate("Form", "Stamp KP"))
        self.reguleringDropdown.setItemText(6, _translate("Form", "Dybde KI"))
        self.reguleringDropdown.setItemText(7, _translate("Form", "Dybde KD"))
        self.reguleringDropdown.setItemText(8, _translate("Form", "Dybde KP"))
        self.reguleringDropdown.setItemText(9, _translate("Form", "TS"))
        self.reguleringDropdown.setItemText(10, _translate("Form", "Alpha"))
import resources_rc
