# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dimmen/repos/fix/Bachelor_GUI/gui/window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1095, 622)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.482955, y1:1, x2:0.489, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(4, 38, 53, 255));")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(29, 20, 1041, 581))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pic = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.pic.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.pic.setText("")
        self.pic.setObjectName("pic")
        self.verticalLayout_5.addWidget(self.pic)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.nextPic = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.nextPic.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.nextPic.setObjectName("nextPic")
        self.verticalLayout.addWidget(self.nextPic)
        self.lastPic = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.lastPic.setStyleSheet("QWidget {\n"
"    background-color: #6E6976;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6E6976;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2E2A33;\n"
"    border: 2px solid #6E6976;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.lastPic.setObjectName("lastPic")
        self.verticalLayout.addWidget(self.lastPic)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nextPic.setText(_translate("Form", "Neste Bilde"))
        self.lastPic.setText(_translate("Form", "Forrige Bilde"))
